import { Injectable, signal, computed } from '@angular/core';

export type Lang = 'et' | 'en';

const TRANSLATIONS: { [key: string]: { et: string; en: string } } = {
  // Nav
  'nav.history': { et: 'Ajalugu', en: 'History' },
  'nav.assessment': { et: 'Hindamine', en: 'Assessment' },
  'nav.subtitle': { et: 'IKT-lepingute hindamine', en: 'ICT Contract Assessment' },
  'nav.dashboard': { et: 'Paneel', en: 'Dashboard' },
  'nav.compare': { et: 'V\u00f5rdlus', en: 'Compare' },
  'nav.brand': { et: 'DORA Vastavuskontroll', en: 'DORA Compliance Checker' },

  // Landing - Hero
  'landing.badge': { et: 'Finantsinspektsioon j\u00e4lgib aktiivselt \u2022 Trahvid kuni 2% k\u00e4ibest', en: 'Finantsinspektsioon actively enforcing \u2022 Fines up to 2% of turnover' },
  'landing.regulation': { et: 'EU m\u00e4\u00e4rus 2022/2554', en: 'EU Regulation 2022/2554' },
  'landing.subtitle': { et: 'Vastavuskontroll', en: 'Compliance Checker' },
  'landing.hero_desc': { et: '38% Eesti finantssektori ettev\u00f5tetest ei vasta veel t\u00e4ielikult DORA n\u00f5uetele. Kontrollige oma IKT-lepinguid enne, kui j\u00e4relevalve seda teeb.', en: '38% of Estonian financial sector companies are not yet fully DORA compliant. Check your ICT contracts before the regulator does.' },
  'landing.cta_try_sample': { et: 'Proovi n\u00e4idislepinguga', en: 'Try with sample contract' },
  'landing.cta_assessment': { et: 'Alusta hindamist', en: 'Start assessment' },
  'landing.description': { et: 'Kontrollige oma IKT-teenuste lepingute vastavust digitaalse tegevuskerksuse m\u00e4\u00e4ruse (DORA) artiklite 28\u201330 n\u00f5uetele.', en: 'Check your ICT service contracts for compliance with the Digital Operational Resilience Act (DORA) Articles 28\u201330.' },
  'landing.cta': { et: 'Alusta hindamist', en: 'Start Assessment' },

  // Landing - Stats
  'landing.stat_fine': { et: 'maksimaalne trahv k\u00e4ibest', en: 'maximum fine of turnover' },
  'landing.stat_noncompliant': { et: 'ettev\u00f5tteid ei vasta veel', en: 'companies not yet compliant' },
  'landing.stat_requirements': { et: 'DORA Art. 30 n\u00f5uet', en: 'DORA Art. 30 requirements' },
  'landing.stat_time': { et: 'lepingu anal\u00fc\u00fcs', en: 'contract analysis' },

  // Landing - Who needs this
  'landing.who_label': { et: 'Kohustuslik vastavus', en: 'Mandatory compliance' },
  'landing.who_title': { et: 'Kellele DORA kehtib?', en: 'Who must comply with DORA?' },
  'landing.who_subtitle': { et: 'Finantsinspektsiooni j\u00e4relevalve all olevad ettev\u00f5tted ja nende IKT-teenusepakkujad', en: 'Companies under Finantsinspektsioon oversight and their ICT service providers' },

  // Sectors
  'landing.sector_banks': { et: 'Pangad', en: 'Banks' },
  'landing.sector_banks_ex': { et: 'LHV, Coop, Bigbank jt', en: 'LHV, Coop, Bigbank etc.' },
  'landing.sector_banks_pain': { et: 'Sajad IKT-lepingud vajavad \u00fclevaatamist DORA Art. 30 n\u00f5uetele', en: 'Hundreds of ICT contracts need review against DORA Art. 30' },
  'landing.sector_insurance': { et: 'Kindlustus', en: 'Insurance' },
  'landing.sector_insurance_ex': { et: 'ERGO, If, Salva jt', en: 'ERGO, If, Salva etc.' },
  'landing.sector_insurance_pain': { et: 'Kolmandate osapoolte riskide haldamine ja lepingute vastavus', en: 'Third-party risk management and contract compliance' },
  'landing.sector_payments': { et: 'Makselahendused', en: 'Payment Services' },
  'landing.sector_payments_ex': { et: 'Wise, Montonio, EveryPay jt', en: 'Wise, Montonio, EveryPay etc.' },
  'landing.sector_payments_pain': { et: 'Kriitiliste pilveteenuste lepingud peavad vastama DORA n\u00f5uetele', en: 'Critical cloud service contracts must meet DORA requirements' },
  'landing.sector_crypto': { et: 'Kr\u00fcptovara', en: 'Crypto Assets' },
  'landing.sector_crypto_ex': { et: 'Litsentseeritud teenusepakkujad', en: 'Licensed service providers' },
  'landing.sector_crypto_pain': { et: 'Uus regulatiivne kohustus \u2014 vastavus tuleb tagada kiiresti', en: 'New regulatory obligation \u2014 compliance must be ensured quickly' },
  'landing.sector_funds': { et: 'Fondivalitsejad', en: 'Fund Managers' },
  'landing.sector_funds_ex': { et: 'Investeerimis\u00fchingud', en: 'Investment firms' },
  'landing.sector_funds_pain': { et: 'Varahalduse IKT-s\u00f5ltuvuste kaardistamine ja lepingute audit', en: 'Mapping ICT dependencies and auditing contracts in asset management' },
  'landing.sector_ict': { et: 'IKT-teenusepakkujad', en: 'ICT Service Providers' },
  'landing.sector_ict_ex': { et: 'IT-ettev\u00f5tted, pilveteenused', en: 'IT companies, cloud services' },
  'landing.sector_ict_pain': { et: 'Teie kliendid n\u00f5uavad DORA-vastavust \u2014 lepingud peavad vastama', en: 'Your clients demand DORA compliance \u2014 contracts must comply' },

  // Landing - Features
  'landing.features_label': { et: 'Platvormi v\u00f5imalused', en: 'Platform Features' },
  'landing.features_title': { et: 'K\u00f5ik, mida vajate DORA vastavuseks', en: 'Everything you need for DORA compliance' },
  'landing.feat_ai_title': { et: 'Claude AI lepinguaudit', en: 'Claude AI Contract Audit' },
  'landing.feat_ai_desc': { et: 'Laadige \u00fcles PDF/DOCX ja saage kohene anal\u00fc\u00fcs DORA Art. 30 vastu.', en: 'Upload PDF/DOCX and get instant analysis against DORA Art. 30.' },
  'landing.feat_fast_title': { et: 'Kiire hindamine', en: 'Quick Assessment' },
  'landing.feat_fast_desc': { et: '37 k\u00fcsimust, tulemused koheselt. Valmis 5 minutiga.', en: '37 questions, instant results. Done in 5 minutes.' },
  'landing.feat_radar_title': { et: 'Radardiagramm', en: 'Radar Chart' },
  'landing.feat_radar_desc': { et: 'Visuaalne vastavusprofiil 15 kategooria l\u00f5ikes.', en: 'Visual compliance profile across 15 categories.' },
  'landing.feat_risk_title': { et: 'Riskimaatriks', en: 'Risk Matrix' },
  'landing.feat_risk_desc': { et: 'Likelihood vs Impact 3x3 heatmap riskide visualiseerimiseks.', en: 'Likelihood vs Impact 3x3 heatmap for risk visualization.' },
  'landing.feat_pdf_title': { et: 'PDF aruanne', en: 'PDF Report' },
  'landing.feat_pdf_desc': { et: 'Professionaalne aruanne printimisel v\u00f5i PDF ekspordiks.', en: 'Professional report for printing or PDF export.' },
  'landing.feat_cert_title': { et: 'Vastavustunnistus', en: 'Compliance Certificate' },
  'landing.feat_cert_desc': { et: 'Sertifikaat ettev\u00f5tte vastavustaseme kinnitamiseks.', en: 'Certificate confirming company compliance level.' },

  // Landing - Steps
  'landing.steps_label': { et: 'Kuidas see t\u00f6\u00f6tab', en: 'How it works' },
  'landing.steps_title': { et: 'Kolm lihtsat sammu', en: 'Three simple steps' },
  'landing.step1_title': { et: 'Laadige leping \u00fcles', en: 'Upload your contract' },
  'landing.step1_desc': { et: 'PDF v\u00f5i DOCX kuni 10 MB, v\u00f5i proovige meie n\u00e4idislepinguga', en: 'PDF or DOCX up to 10 MB, or try our sample contract' },
  'landing.step2_title': { et: 'AI anal\u00fc\u00fcsib', en: 'AI analyzes' },
  'landing.step2_desc': { et: 'Claude AI kontrollib lepingut DORA Art. 30 n\u00f5uete vastu', en: 'Claude AI checks contract against DORA Art. 30 requirements' },
  'landing.step3_title': { et: 'Saate tulemused', en: 'Get results' },
  'landing.step3_desc': { et: 'Detailne aruanne puudustega, tsitaatidega ja soovitustega', en: 'Detailed report with gaps, quotes and recommendations' },
  'landing.step1.title': { et: 'Sisesta andmed', en: 'Enter Data' },
  'landing.step1.desc': { et: 'Ettev\u00f5tte nimi ja IKT-lepingu nimetus', en: 'Company name and ICT contract title' },
  'landing.step2.title': { et: 'Vasta k\u00fcsimustele', en: 'Answer Questions' },
  'landing.step2.desc': { et: '15 k\u00fcsimust 9 DORA kategooriast', en: '15 questions across 9 DORA categories' },
  'landing.step3.title': { et: 'Saa tulemused', en: 'Get Results' },
  'landing.step3.desc': { et: 'Vastavusskoor ja soovitused', en: 'Compliance score and recommendations' },

  // Landing - Pillars
  'landing.pillars_label': { et: 'DORA raamistik', en: 'DORA Framework' },
  'landing.pillars_title': { et: '5 sammast', en: '5 Pillars' },
  'landing.pillars_desc': { et: 'Digitaalse tegevuskerksuse m\u00e4\u00e4ruse viis p\u00f5hisammast', en: 'Five core pillars of the Digital Operational Resilience Act' },
  'landing.pillar_risk': { et: 'IKT riskihaldus', en: 'ICT Risk Management' },
  'landing.pillar_incident': { et: 'Intsidendid', en: 'Incidents' },
  'landing.pillar_testing': { et: 'Testimine', en: 'Testing' },
  'landing.pillar_thirdparty': { et: 'Kolmandad osapooled', en: 'Third Parties' },
  'landing.pillar_info': { et: 'Info jagamine', en: 'Information Sharing' },
  'landing.active': { et: 'Aktiivne', en: 'Active' },
  'landing.soon': { et: 'Peagi', en: 'Soon' },
  'landing.categories': { et: 'Hindamise valdkonnad', en: 'Assessment Areas' },
  'landing.pillars': { et: 'DORA 5 sammast', en: 'DORA 5 Pillars' },

  // Landing - Category badges
  'landing.cat_service': { et: 'Teenustase', en: 'Service Level' },
  'landing.cat_exit': { et: 'V\u00e4ljumisstrateegia', en: 'Exit Strategy' },
  'landing.cat_audit': { et: 'Audit', en: 'Audit' },
  'landing.cat_incident': { et: 'Intsidendid', en: 'Incidents' },
  'landing.cat_data': { et: 'Andmekaitse', en: 'Data Protection' },
  'landing.cat_subcontracting': { et: 'Allhange', en: 'Subcontracting' },
  'landing.cat_risk': { et: 'Risk', en: 'Risk' },
  'landing.cat_legal': { et: '\u00d5igus', en: 'Legal' },
  'landing.cat_continuity': { et: 'Pidevus', en: 'Continuity' },
  'landing.cat_recruitment': { et: 'V\u00e4rbamine', en: 'Recruitment' },
  'landing.cat_financial': { et: 'Finantsaruandlus', en: 'Financial Reporting' },
  'landing.cat_ict_risk': { et: 'IKT riskihaldus', en: 'ICT Risk Management' },
  'landing.cat_incident_ext': { et: 'Intsidendid (laiendatud)', en: 'Incidents (Extended)' },
  'landing.cat_testing': { et: 'Testimine', en: 'Testing' },
  'landing.cat_info': { et: 'Info jagamine', en: 'Information Sharing' },

  // Landing - Timeline
  'landing.timeline_label': { et: 'Regulatsiooni ajajoon', en: 'Regulation Timeline' },
  'landing.timeline_title': { et: 'DORA t\u00e4htp\u00e4evad', en: 'DORA Milestones' },
  'landing.tl_proposal_title': { et: 'DORA ettepanek', en: 'DORA Proposal' },
  'landing.tl_proposal_desc': { et: 'Euroopa Komisjon avaldab DORA m\u00e4\u00e4ruse ettepaneku', en: 'European Commission publishes DORA regulation proposal' },
  'landing.tl_adoption_title': { et: 'DORA vastuv\u00f5tmine', en: 'DORA Adoption' },
  'landing.tl_adoption_desc': { et: 'Euroopa Parlament kiidab m\u00e4\u00e4ruse heaks', en: 'European Parliament approves the regulation' },
  'landing.tl_force_title': { et: 'J\u00f5ustumine', en: 'Entry into Force' },
  'landing.tl_force_desc': { et: 'DORA m\u00e4\u00e4rus j\u00f5ustub ametlikult', en: 'DORA regulation officially enters into force' },
  'landing.tl_apply_title': { et: 'Kohaldamine', en: 'Application' },
  'landing.tl_apply_desc': { et: 'T\u00e4ielik kohaldamine k\u00f5igile finantssektori ettev\u00f5tetele', en: 'Full application to all financial sector companies' },
  'landing.tl_enforce_title': { et: 'Aktiivne j\u00e4relevalve', en: 'Active Enforcement' },
  'landing.tl_enforce_desc': { et: 'Finantsinspektsioon alustab s\u00fcsteemset DORA auditit. Trahvid kuni 2% k\u00e4ibest.', en: 'Finantsinspektsioon begins systematic DORA audits. Fines up to 2% of turnover.' },

  // Landing - Marquee
  'landing.marquee_label': { et: 'Sobib igale finantssektori ettev\u00f5ttele', en: 'Suitable for all financial sector companies' },
  'landing.m_banks': { et: 'Pangad', en: 'Banks' },
  'landing.m_payments': { et: 'Makseasutused', en: 'Payment Institutions' },
  'landing.m_investment': { et: 'Investeerimis\u00fchingud', en: 'Investment Firms' },
  'landing.m_insurance': { et: 'Kindlustusseltsid', en: 'Insurance Companies' },
  'landing.m_funds': { et: 'Fondivalitsejad', en: 'Fund Managers' },
  'landing.m_audit': { et: 'Auditifirmad', en: 'Audit Firms' },
  'landing.m_ict': { et: 'IKT-teenusepakkujad', en: 'ICT Providers' },
  'landing.m_cloud': { et: 'Pilveteenused', en: 'Cloud Services' },
  'landing.m_cyber': { et: 'K\u00fcberturbe ettev\u00f5tted', en: 'Cybersecurity Firms' },
  'landing.m_fintech': { et: 'Fintech startupid', en: 'Fintech Startups' },

  // Landing - Reviews
  'landing.reviews_label': { et: 'Tagasiside', en: 'Testimonials' },
  'landing.reviews_title': { et: 'Mida kliendid \u00fctlevad', en: 'What clients say' },
  'landing.review1_text': { et: 'AI lepinguaudit s\u00e4\u00e4stis meile n\u00e4dalaid konsultandi tasu. Saime kohe teada, millised klauslid puuduvad.', en: 'AI contract audit saved us weeks of consultant fees. We instantly knew which clauses were missing.' },
  'landing.review1_role': { et: 'IT-vastavusjuht, fintech-ettev\u00f5te', en: 'IT Compliance Manager, fintech company' },
  'landing.review2_text': { et: 'Radardiagramm annab suurep\u00e4rase \u00fclevaate. N\u00fc\u00fcd teame t\u00e4pselt, kus peame parandusi tegema.', en: 'Radar chart gives an excellent overview. Now we know exactly where improvements are needed.' },
  'landing.review2_role': { et: 'Riskijuht, kindlustusselts', en: 'Risk Manager, insurance company' },
  'landing.review3_text': { et: 'Kasutame seda regulaarselt k\u00f5igi oma IKT-lepingute kontrollimiseks. V\u00e4ga professionaalne.', en: 'We use it regularly to check all our ICT contracts. Very professional.' },
  'landing.review3_role': { et: 'IKT lepingute haldur, pank', en: 'ICT Contract Manager, bank' },

  // Landing - Trust
  'landing.trust_title': { et: 'Loodud Eesti finantssektorile', en: 'Built for Estonian Financial Sector' },
  'landing.trust_desc': { et: 'P\u00f5hineb DORA m\u00e4\u00e4rusel 2022/2554. Eestikeelne. Andmed ei lahku Euroopa Liidust.', en: 'Based on DORA regulation 2022/2554. In Estonian. Data stays within the EU.' },
  'landing.trust_eu_data': { et: 'Andmed EL-is', en: 'Data in EU' },

  // Landing - EU compliance
  'landing.eu_compliance': { et: 'EU regulatsioonide vastavus', en: 'EU Regulatory Compliance' },
  'landing.eu_desc_dora': { et: 'Toetab', en: 'Supports' },
  'landing.eu_desc_nis2': { et: 'tugi on tulemas.', en: 'support coming soon.' },

  // Landing - Final CTA
  'landing.final_cta_title': { et: 'Kas teie IKT-lepingud vastavad DORA n\u00f5uetele?', en: 'Do your ICT contracts meet DORA requirements?' },
  'landing.final_cta_desc': { et: 'Tehke esimene anal\u00fc\u00fcs tasuta. Saate koheselt teada, millised puudused tuleb k\u00f5rvaldada enne Finantsinspektsiooni auditit.', en: 'Run your first analysis for free. Instantly learn which gaps need fixing before Finantsinspektsioon audits.' },

  // Assessment
  'assessment.title': { et: 'DORA vastavuse hindamine', en: 'DORA Compliance Assessment' },
  'assessment.step_data': { et: 'Andmed', en: 'Data' },
  'assessment.step_questions': { et: 'K\u00fcsimused', en: 'Questions' },
  'assessment.step_results': { et: 'Tulemused', en: 'Results' },
  'assessment.company': { et: 'Ettev\u00f5tte andmed', en: 'Company Information' },
  'assessment.company_name': { et: 'Ettev\u00f5tte nimi', en: 'Company Name' },
  'assessment.contract_name': { et: 'Lepingu nimetus', en: 'Contract Name' },
  'assessment.submit': { et: 'Esita hindamine', en: 'Submit Assessment' },
  'assessment.submitting': { et: 'Hindamine...', en: 'Assessing...' },
  'assessment.score_preview': { et: 'Eeldatav skoor', en: 'Expected Score' },
  'assessment.yes': { et: 'Jah', en: 'Yes' },
  'assessment.no': { et: 'Ei', en: 'No' },
  'assessment.questions_suffix': { et: 'k\u00fcsimust', en: 'questions' },
  'assessment.question_suffix': { et: 'k\u00fcsimus', en: 'question' },
  'assessment.sector': { et: 'Sektor', en: 'Sector' },
  'assessment.select_sector': { et: 'Valige sektor...', en: 'Select sector...' },
  'assessment.scenario_ideal': { et: 'Ideaalne leping', en: 'Ideal contract' },
  'assessment.scenario_average': { et: 'Keskmine leping', en: 'Average contract' },
  'assessment.scenario_weak': { et: 'N\u00f5rk leping', en: 'Weak contract' },
  'assessment.clear': { et: 'T\u00fchjenda', en: 'Clear' },

  // Results
  'results.loading': { et: 'Tulemuste laadimine...', en: 'Loading results...' },
  'results.percent': { et: 'protsenti', en: 'percent' },
  'results.compliant': { et: 'vastav', en: 'compliant' },
  'results.non_compliant': { et: 'mittevastav', en: 'non-compliant' },
  'results.total': { et: 'kokku', en: 'total' },
  'results.profile': { et: 'Vastavuse profiil', en: 'Compliance Profile' },
  'results.risk_matrix': { et: 'Riskimaatriks', en: 'Risk Matrix' },
  'results.low': { et: 'Madal', en: 'Low' },
  'results.medium': { et: 'Keskmine', en: 'Medium' },
  'results.high': { et: 'K\u00f5rge', en: 'High' },
  'results.low_risk': { et: 'Madal risk', en: 'Low Risk' },
  'results.med_risk': { et: 'Keskmine', en: 'Medium' },
  'results.high_risk': { et: 'K\u00f5rge risk', en: 'High Risk' },
  'results.likelihood': { et: 'T\u00f5en\u00e4osus', en: 'Likelihood' },
  'results.impact': { et: 'M\u00f5ju', en: 'Impact' },
  'results.pillars': { et: 'DORA 5 sammast', en: 'DORA 5 Pillars' },
  'results.detail': { et: 'Detailne \u00fclevaade', en: 'Detailed Overview' },
  'results.recommendation': { et: 'Soovitus', en: 'Recommendation' },
  'results.priority': { et: 'Prioriteetne tegevuskava', en: 'Priority Action Plan' },
  'results.gaps': { et: 'puudust', en: 'gaps' },
  'results.critical': { et: 'Kriitiline', en: 'Critical' },
  'results.important': { et: 'Oluline', en: 'Important' },
  'results.download_pdf': { et: 'Laadi PDF', en: 'Download PDF' },
  'results.new_assessment': { et: 'Uus hindamine', en: 'New Assessment' },
  'results.history': { et: 'Ajalugu', en: 'History' },
  'results.green': { et: 'Vastav', en: 'Compliant' },
  'results.yellow': { et: 'Osaliselt vastav', en: 'Partially Compliant' },
  'results.red': { et: 'Mittevastav', en: 'Non-Compliant' },
  'results.certificate': { et: 'Tunnistus', en: 'Certificate' },
  'results.fine_risk': { et: 'Trahviriski hinnang', en: 'Fine Risk Estimate' },
  'results.fine_red': { et: 'K\u00f5rge risk \u2014 Finantsinspektsioon v\u00f5ib m\u00e4\u00e4rata trahvi kuni 2% aastasest k\u00e4ibest', en: 'High risk \u2014 Finantsinspektsioon may impose a fine up to 2% of annual turnover' },
  'results.fine_yellow': { et: 'Keskmine risk \u2014 Ettekirjutuse ja m\u00e4rkuste risk on olemas', en: 'Medium risk \u2014 Risk of prescriptions and remarks exists' },
  'results.fine_green': { et: 'Madal risk \u2014 Vastavus on tagatud, j\u00e4tkake regulaarset \u00fclevaatust', en: 'Low risk \u2014 Compliance is ensured, continue regular review' },
  'results.fine_note': { et: 'Hinnang p\u00f5hineb DORA m\u00e4\u00e4rusel 2022/2554 ja Finantsinspektsiooni j\u00e4relevalvepraktikal', en: 'Estimate based on DORA regulation 2022/2554 and Finantsinspektsioon supervisory practice' },
  'results.of_turnover': { et: 'k\u00e4ibest', en: 'of turnover' },
  'results.cta_contract_title': { et: 'Kontrollige ka oma IKT-lepinguid', en: 'Also check your ICT contracts' },
  'results.cta_contract_desc': { et: 'Claude AI anal\u00fc\u00fcsib lepingut DORA Art. 30 n\u00f5uete vastu ja annab soovitused puuduste k\u00f5rvaldamiseks', en: 'Claude AI analyzes contracts against DORA Art. 30 requirements and provides recommendations for fixing gaps' },
  'results.cta_contract_btn': { et: 'Anal\u00fc\u00fcsi lepingut', en: 'Analyze contract' },

  // History
  'history.title': { et: 'Hindamiste ajalugu', en: 'Assessment History' },
  'history.total': { et: 'hindamist kokku', en: 'total assessments' },
  'history.avg_score': { et: 'Keskmine skoor', en: 'Average Score' },
  'history.compliant': { et: 'Vastavad', en: 'Compliant' },
  'history.partial': { et: 'Osaliselt', en: 'Partial' },
  'history.non_compliant': { et: 'Mittevastav', en: 'Non-Compliant' },
  'history.trend': { et: 'Skoori trend', en: 'Score Trend' },
  'history.empty_title': { et: 'Ajalugu on t\u00fchi', en: 'History is Empty' },
  'history.empty_desc': { et: 'Te pole veel \u00fchtegi hindamist l\u00e4bi viinud.', en: 'You haven\u2019t completed any assessments yet.' },
  'history.first': { et: 'Alusta esimest hindamist', en: 'Start First Assessment' },
  'history.clear': { et: 'Kustuta ajalugu', en: 'Clear History' },
  'history.new': { et: 'Uus hindamine', en: 'New Assessment' },

  // Contract Analysis
  'nav.contract': { et: 'Lepingu audit', en: 'Contract Audit' },
  'contract.title': { et: 'Lepingu anal\u00fc\u00fcs', en: 'Contract Analysis' },
  'contract.subtitle': { et: 'DORA Art. 30 n\u00f5uete kontroll Claude AI abil', en: 'DORA Art. 30 compliance check with Claude AI' },
  'contract.upload_label': { et: 'Lae \u00fcles leping (PDF v\u00f5i DOCX)', en: 'Upload contract (PDF or DOCX)' },
  'contract.upload_hint': { et: 'Maksimaalselt 10 MB', en: 'Maximum 10 MB' },
  'contract.company_name': { et: 'Ettev\u00f5tte nimi', en: 'Company Name' },
  'contract.contract_name': { et: 'Lepingu nimetus', en: 'Contract Name' },
  'contract.analyze': { et: 'Anal\u00fc\u00fcsi lepingut', en: 'Analyze Contract' },
  'contract.analyzing': { et: 'Anal\u00fc\u00fcsin lepingut...', en: 'Analyzing contract...' },
  'contract.ai_note': { et: 'Claude AI anal\u00fc\u00fcsib lepingut DORA Art. 30 n\u00f5uete vastu. See v\u00f5ib v\u00f5tta kuni 1 minut.', en: 'Claude AI is analyzing the contract against DORA Art. 30 requirements. This may take up to 1 minute.' },
  'contract.results': { et: 'Anal\u00fc\u00fcsi tulemused', en: 'Analysis Results' },
  'contract.score': { et: 'Vastavusskoor', en: 'Compliance Score' },
  'contract.found': { et: 'Leitud', en: 'Found' },
  'contract.missing': { et: 'Puudu', en: 'Missing' },
  'contract.partial': { et: 'Osaliselt', en: 'Partial' },
  'contract.quote': { et: 'Tsitaat lepingust', en: 'Quote from contract' },
  'contract.recommendation': { et: 'Soovitus', en: 'Recommendation' },
  'contract.new_analysis': { et: 'Uus anal\u00fc\u00fcs', en: 'New Analysis' },
  'contract.drag_drop': { et: 'Lohista fail siia v\u00f5i kliki valimiseks', en: 'Drag file here or click to select' },
  'contract.file_selected': { et: 'Fail valitud', en: 'File selected' },
  'contract.error': { et: 'Anal\u00fc\u00fcs eba\u00f5nnestus. Palun proovige uuesti.', en: 'Analysis failed. Please try again.' },
  'contract.summary': { et: 'Kokkuv\u00f5te', en: 'Summary' },
  'contract.download_pdf': { et: 'Laadi PDF', en: 'Download PDF' },
  'contract.sample_title': { et: 'Pole lepingut k\u00e4ep\u00e4rast?', en: 'No contract at hand?' },
  'contract.sample_desc': { et: 'Laadi n\u00e4idis IKT-leping testimiseks', en: 'Load a sample ICT contract for testing' },
  'contract.load_sample': { et: 'Laadi n\u00e4idisleping', en: 'Load sample contract' },
  'contract.download_sample': { et: 'Vaata PDF', en: 'View PDF' },
  'contract.risk_areas': { et: 'K\u00f5ige riskantsemad kohad', en: 'Highest Risk Areas' },
  'contract.risk_areas_desc': { et: 'Need n\u00f5uded vajavad kohest t\u00e4helepanu', en: 'These requirements need immediate attention' },
  'contract.auto_demo_title': { et: 'N\u00e4idislepingu automaatne anal\u00fc\u00fcs', en: 'Automatic sample contract analysis' },
  'contract.auto_demo_desc': { et: 'Laadime n\u00e4idislepingu ja alustame anal\u00fc\u00fcsi automaatselt...', en: 'Loading sample contract and starting analysis automatically...' },
  'contract.suggested_clauses': { et: 'Soovituslikud lepinguklauslid', en: 'Suggested contract clauses' },
  'contract.suggested_clauses_desc': { et: 'Lisage need klauslid oma lepingusse puuduste k\u00f5rvaldamiseks', en: 'Add these clauses to your contract to fix gaps' },
  'contract.reg_references': { et: 'Regulatiivsed viited', en: 'Regulatory References' },
  'contract.guidelines': { et: 'juhised', en: 'Guidelines' },
  'contract.share_title': { et: 'Saada tulemused e-mailile', en: 'Send results to email' },
  'contract.share_desc': { et: 'Saame saata teile kokkuv\u00f5tte ja uuendused', en: 'We can send you a summary and updates' },
  'contract.email_placeholder': { et: 'teie@ettevote.ee', en: 'your@company.com' },
  'contract.send': { et: 'Saada', en: 'Send' },
  'contract.email_saved': { et: 'E-mail salvestatud! Saadame teile tulemused.', en: 'Email saved! We will send you the results.' },

  // Nav - Code Analysis
  'nav.code': { et: 'Koodi audit', en: 'Code Audit' },

  // Code Analysis
  'code.badge': { et: 'ULTRA MODE \u2022 Halastamatu koodiaudit', en: 'ULTRA MODE \u2022 Ruthless Code Audit' },
  'code.title': { et: 'Koodi audit', en: 'Code Audit' },
  'code.subtitle': { et: 'AI-genereeritud koodi tuvastamine, turvaaaukude leidmine ja finantsilise m\u00f5ju hindamine. Knight Capital kaotas 45 minutiga $460M \u2014 sinu kood v\u00f5ib olla j\u00e4rgmine.', en: 'AI-generated code detection, vulnerability scanning and financial impact assessment. Knight Capital lost $460M in 45 minutes \u2014 your code could be next.' },
  'code.company': { et: 'Ettev\u00f5tte nimi', en: 'Company Name' },
  'code.revenue': { et: 'Aastane k\u00e4ive (\u20ac)', en: 'Annual Revenue (\u20ac)' },
  'code.revenue_hint': { et: 'Kahjude arvutamiseks \u2014 t\u00e4psem k\u00e4ive = t\u00e4psem anal\u00fc\u00fcs', en: 'For loss calculations \u2014 more accurate revenue = more accurate analysis' },
  'code.drop_files': { et: 'Lohista koodifailid siia v\u00f5i kliki valimiseks', en: 'Drag code files here or click to select' },
  'code.files_selected': { et: 'faili valitud', en: 'files selected' },
  'code.start_analysis': { et: 'K\u00e4ivita audit', en: 'Start Audit' },
  'code.analyzing_iteration': { et: 'Anal\u00fc\u00fcsin \u2014 iteratsioon', en: 'Analyzing \u2014 iteration' },
  'code.iteration': { et: 'Iteratsioon', en: 'Iteration' },
  'code.next_iteration': { et: 'J\u00e4rgmine iteratsioon', en: 'Next iteration' },
  'code.ai_percentage': { et: 'AI-genereeritud kood', en: 'AI-Generated Code' },
  'code.ai_warning': { et: 'AI-genereeritud kood suurendab teadmatust ja hoolduskulusid eksponentsiaalselt', en: 'AI-generated code increases uncertainty and maintenance costs exponentially' },
  'code.verdict': { et: '\u00dcldine hinnang', en: 'Overall Verdict' },
  'code.total_exposure': { et: 'Kogu finantsrisk', en: 'Total Financial Exposure' },
  'code.ai_indicators': { et: 'AI-genereerimise tunnused', en: 'AI Generation Indicators' },
  'code.security_vulns': { et: 'Turvaaaugud', en: 'Security Vulnerabilities' },
  'code.exploit': { et: '\u00c4rakasutamine', en: 'Exploit' },
  'code.real_world': { et: 'Reaalne paralleel', en: 'Real-World Parallel' },
  'code.fix': { et: 'Parandus', en: 'Fix' },
  'code.fix_critique': { et: 'Miks see parandus tavaliselt eba\u00f5nnestub', en: 'Why this fix usually fails' },
  'code.quality_issues': { et: 'Koodikvaliteedi probleemid', en: 'Code Quality Issues' },
  'code.financial_deep': { et: 'Finantsriski s\u00fcvanal\u00fc\u00fcs', en: 'Financial Risk Deep Dive' },
  'code.annual_loss': { et: 'Hinnanguline aastane kahju', en: 'Estimated Annual Loss' },
  'code.catastrophe_12m': { et: 'Katastroofi t\u00f5en\u00e4osus 12 kuud', en: 'Catastrophe Probability 12mo' },
  'code.compliance_risk': { et: 'Vastavuse risk', en: 'Compliance Risk' },
  'code.new_analysis': { et: 'Uus audit', en: 'New Audit' },
  'code.mock_title': { et: 'Proovi n\u00E4idis-koodibaasiga', en: 'Try with mock codebase' },
  'code.mock_badge': { et: 'Kiire demo', en: 'Quick demo' },
  'code.mock_desc': { et: 'Vali n\u00E4idis-koodibaas ja kvaliteeditase. N\u00E4ed kohe, mida halva koodi hooldamine ettev\u00F5ttele maksma l\u00E4heb.', en: 'Pick a mock codebase and quality level. See immediately what maintaining bad code costs your company.' },
  'code.quality_level': { et: 'Hindamise vaatenurk', en: 'Assessment lens' },
  'code.quality_lens_hint': { et: 'M\u00F5jutab anal\u00FC\u00FCsi fookust ja kahju arvutusi', en: 'Affects analysis focus and damage calculations' },
  'code.load_mock': { et: 'Laadi n\u00E4idis-koodibaas', en: 'Load mock codebase' },
  'code.hourly_rate': { et: 'Arendaja tunnihind (\u20AC)', en: 'Developer hourly rate (\u20AC)' },
  'code.hourly_hint': { et: 'Eesti keskmine: \u20AC65\u201395/h. PM-id armastavad seda numbrit.', en: 'Estonian average: \u20AC65\u201395/h. PMs love this number.' },
  'code.team_size': { et: 'Meeskonna suurus (arendajaid)', en: 'Team size (developers)' },
  'code.dev_months': { et: 'Projekti kestus (kuud)', en: 'Project duration (months)' },
  'code.pm_dashboard': { et: 'PM M\u00F5juanal\u00FC\u00FCs', en: 'PM Impact Dashboard' },
  'code.pm_wasted_hours': { et: 'Raisatud tunnid', en: 'Wasted Hours' },
  'code.pm_wasted_eur': { et: 'Raisatud eurod', en: 'Wasted EUR' },
  'code.pm_fix_hours': { et: 'Parandamise tunnid', en: 'Fix Hours' },
  'code.pm_fix_cost': { et: 'Paranduskulu', en: 'Fix Cost' },
  'code.pm_team_impact': { et: 'Meeskonna m\u00F5ju', en: 'Team Impact' },
  'code.pm_brutal': { et: 'Karm t\u00F5de', en: 'The Brutal Truth' },

  // Nav - Simulator
  'nav.simulator': { et: 'Simulaator', en: 'Simulator' },

  // Incident Simulator
  'sim.badge': { et: 'Unikaalne t\u00f6\u00f6riist \u2022 Intsidendisimulaator', en: 'Unique Tool \u2022 Incident Simulator' },
  'sim.title': { et: 'IKT intsidendi simulaator', en: 'ICT Incident Simulator' },
  'sim.subtitle': { et: 'Simuleerige reaalseid k\u00fcberintsidente ja vaadake, kuidas teie DORA vastavus p\u00fc\u00fcab. N\u00e4ete t\u00e4pselt, millised l\u00fcngad muutuvad haavatavusteks.', en: 'Simulate real-world cyber incidents and see how your DORA compliance holds up. See exactly which gaps become vulnerabilities.' },
  'sim.no_data_title': { et: 'Hindamisandmed puuduvad', en: 'No Assessment Data' },
  'sim.no_data_desc': { et: 'Simulaatori kasutamiseks tehke k\u00f5igepealt DORA vastavuse hindamine.', en: 'Complete a DORA compliance assessment first to use the simulator.' },
  'sim.start_assessment': { et: 'Alusta hindamist', en: 'Start Assessment' },
  'sim.choose_scenario': { et: 'Valige intsidendi stsenaarium', en: 'Choose an Incident Scenario' },
  'sim.choose_desc': { et: 'Iga stsenaarium p\u00f5hineb reaalsetel juhtumitel ja kaardistab m\u00f5ju teie DORA vastavusprofiilile.', en: 'Each scenario is based on real incidents and maps impact to your DORA compliance profile.' },
  'sim.areas_affected': { et: 'valdkonda m\u00f5jutatud', en: 'areas affected' },
  'sim.using_assessment': { et: 'Kasutatav hindamine', en: 'Using assessment' },
  'sim.back': { et: 'Tagasi stsenaariumite juurde', en: 'Back to scenarios' },
  'sim.exposure': { et: 'Haavatavus', en: 'Exposure' },
  'sim.gaps_exploited': { et: '\u00c4rakasutatud l\u00fcngad', en: 'Gaps Exploited' },
  'sim.protected': { et: 'Kaitstud', en: 'Protected' },
  'sim.response_time': { et: 'Taastumisaeg', en: 'Recovery Time' },
  'sim.days': { et: 'p', en: 'd' },
  'sim.day': { et: 'P\u00e4ev', en: 'Day' },
  'sim.regulatory_outcome': { et: 'Regulatiivne tagaj\u00e4rg', en: 'Regulatory Outcome' },
  'sim.outcome_FINE': { et: 'Trahv', en: 'Fine' },
  'sim.outcome_FINE_desc': { et: 'Finantsinspektsioon m\u00e4\u00e4rab t\u00f5en\u00e4oliselt trahvi. Teie DORA vastavusel on olulisi l\u00fcnki, mis v\u00f5imaldasid intsidendi toimumist.', en: 'Finantsinspektsioon will likely impose a fine. Your DORA compliance has significant gaps that enabled the incident.' },
  'sim.outcome_PRESCRIPTION': { et: 'Ettekirjutus', en: 'Prescription' },
  'sim.outcome_PRESCRIPTION_desc': { et: 'Finantsinspektsioon esitab ettekirjutuse koos t\u00e4htajaga puuduste k\u00f5rvaldamiseks. Trahvi v\u00f5idakse m\u00e4\u00e4rata, kui n\u00f5udeid ei t\u00e4ideta.', en: 'Finantsinspektsioon will issue a prescription with a deadline to fix deficiencies. Fines may follow if requirements are not met.' },
  'sim.outcome_WARNING': { et: 'Hoiatus', en: 'Warning' },
  'sim.outcome_WARNING_desc': { et: 'T\u00f5en\u00e4oliselt saate hoiatuse ja soovitused. Vastavus on enamasti tagatud, kuid m\u00f5ned kohad vajavad t\u00e4iustamist.', en: 'You will likely receive a warning and recommendations. Compliance is mostly ensured but some areas need improvement.' },
  'sim.outcome_COMPLIANT': { et: 'Vastav', en: 'Compliant' },
  'sim.outcome_COMPLIANT_desc': { et: 'Teie DORA vastavus on tugev. Intsident k\u00e4sitletakse korrektselt ning regulatiivset sekkumist ei ole oodata.', en: 'Your DORA compliance is strong. The incident would be handled correctly and no regulatory intervention is expected.' },
  'sim.max_fine': { et: 'Maksimaalne trahv', en: 'Maximum fine' },
  'sim.of_turnover': { et: 'aastasest k\u00e4ibest', en: 'of annual turnover' },
  'sim.timeline': { et: 'Intsidendi ajajoon', en: 'Incident Timeline' },
  'sim.exploited_gaps': { et: '\u00e4rakasutatud l\u00fcnka', en: 'exploited gaps' },
  'sim.protected_areas': { et: 'kaitstud valdkonda', en: 'protected areas' },
  'sim.real_world': { et: 'Reaalne n\u00e4ide', en: 'Real-World Example' },
  'sim.loss': { et: 'Kahju', en: 'Loss' },
  'sim.try_another': { et: 'Proovi teist stsenaariumit', en: 'Try Another Scenario' },
  'sim.improve_score': { et: 'Paranda vastavust', en: 'Improve Compliance' },

  // Scenarios
  'sim.scenario_ransomware': { et: 'Lunavararunnak', en: 'Ransomware Attack' },
  'sim.scenario_ransomware_desc': { et: 'K\u00fcberrundajad kr\u00fcpteerivad teie IKT-s\u00fcsteemid ja n\u00f5uavad lunaraha. Teenused on maas.', en: 'Attackers encrypt your ICT systems and demand ransom. Services are down.' },
  'sim.scenario_cloud_outage': { et: 'Pilveteenuse katkestus', en: 'Cloud Service Outage' },
  'sim.scenario_cloud_outage_desc': { et: 'Teie p\u00f5hiline pilveteenuse pakkuja kogeb pikaajalist katkestust.', en: 'Your primary cloud provider experiences an extended outage.' },
  'sim.scenario_data_breach': { et: 'Andmeleke', en: 'Data Breach' },
  'sim.scenario_data_breach_desc': { et: 'Klientide isikuandmed ja finantsandmed lekivad avalikuks.', en: 'Customer personal and financial data is exposed publicly.' },
  'sim.scenario_supply_chain': { et: 'Tarneahela r\u00fcnnak', en: 'Supply Chain Attack' },
  'sim.scenario_supply_chain_desc': { et: 'Teie IKT-teenusepakkuja tarkvara on kompromiteeritud tagauksega.', en: 'Your ICT provider\'s software is compromised with a backdoor.' },
  'sim.scenario_insider_threat': { et: 'Sisemine oht', en: 'Insider Threat' },
  'sim.scenario_insider_threat_desc': { et: 'Endine t\u00f6\u00f6taja pääseb ligi konfidentsiaalsetele andmetele ja s\u00fcsteemidele.', en: 'Former employee accesses confidential data and systems.' },
  'sim.scenario_api_attack': { et: 'API r\u00fcnnak', en: 'API Attack' },
  'sim.scenario_api_attack_desc': { et: 'R\u00fcndajad kasutavad \u00e4ra teie avaliku API haavatavusi massiliseks andmete kogumiseks.', en: 'Attackers exploit your public API vulnerabilities for mass data extraction.' },

  // Timeline events - Ransomware
  'sim.tl_ransomware_detection': { et: 'Intsidendi tuvastamine', en: 'Incident Detection' },
  'sim.tl_ransomware_detection_desc': { et: 'S\u00fcsteemid muutuvad k\u00e4ttesaamatuks. IT-meeskond tuvastab lunavara.', en: 'Systems become inaccessible. IT team identifies ransomware.' },
  'sim.tl_ransomware_containment': { et: 'Isoleerimine', en: 'Containment' },
  'sim.tl_ransomware_containment_desc': { et: 'Nakatunud s\u00fcsteemid isoleeritakse. Hinnang leviku ulatusele.', en: 'Infected systems isolated. Assessment of spread extent.' },
  'sim.tl_ransomware_notification': { et: 'Teavitamine', en: 'Notification' },
  'sim.tl_ransomware_notification_desc': { et: 'Finantsinspektsioon ja kliendid teavitatakse intsidendist (DORA Art. 19).', en: 'Finantsinspektsioon and clients notified of incident (DORA Art. 19).' },
  'sim.tl_ransomware_investigation': { et: 'Uurimine', en: 'Investigation' },
  'sim.tl_ransomware_investigation_desc': { et: 'Forenseeriline anal\u00fc\u00fcs. Sissep\u00e4\u00e4su vektori tuvastamine.', en: 'Forensic analysis. Entry vector identification.' },
  'sim.tl_ransomware_recovery': { et: 'Taastamine', en: 'Recovery' },
  'sim.tl_ransomware_recovery_desc': { et: 'S\u00fcsteemide taastamine varukoopiatest. Teenuste j\u00e4rk-j\u00e4rguline taastamine.', en: 'System restoration from backups. Gradual service recovery.' },
  'sim.tl_ransomware_regulatory': { et: 'Regulatiivne j\u00e4relkontroll', en: 'Regulatory Follow-up' },
  'sim.tl_ransomware_regulatory_desc': { et: 'Finantsinspektsiooni audit DORA vastavuse kohta. Otsus sanktsioonide osas.', en: 'Finantsinspektsioon audit on DORA compliance. Decision on sanctions.' },

  // Timeline events - Cloud outage
  'sim.tl_cloud_outage_detection': { et: 'Katkestuse tuvastamine', en: 'Outage Detection' },
  'sim.tl_cloud_outage_detection_desc': { et: 'Monitooring tuvastab pilveteenuse katkestuse. Kliendid teatavad probleemidest.', en: 'Monitoring detects cloud service outage. Clients report issues.' },
  'sim.tl_cloud_outage_containment': { et: 'Eskaleermine', en: 'Escalation' },
  'sim.tl_cloud_outage_containment_desc': { et: '\u00dchendusse astumine teenusepakkujaga. BCP aktiveerimine.', en: 'Contact with provider. BCP activation.' },
  'sim.tl_cloud_outage_notification': { et: 'Klientide teavitamine', en: 'Client Notification' },
  'sim.tl_cloud_outage_notification_desc': { et: 'Klientide ja regulaatori teavitamine teenuse katkestusest.', en: 'Notification of clients and regulator about service disruption.' },
  'sim.tl_cloud_outage_investigation': { et: 'M\u00f5juanal\u00fc\u00fcs', en: 'Impact Analysis' },
  'sim.tl_cloud_outage_investigation_desc': { et: 'Kahjude ja m\u00f5jutatud teenuste kaardistamine.', en: 'Mapping of damages and affected services.' },
  'sim.tl_cloud_outage_recovery': { et: 'Teenuse taastamine', en: 'Service Recovery' },
  'sim.tl_cloud_outage_recovery_desc': { et: 'Teenuse taastamine p\u00e4rast pakkuja parandust v\u00f5i alternatiivile \u00fcleminek.', en: 'Service recovery after provider fix or migration to alternative.' },
  'sim.tl_cloud_outage_regulatory': { et: 'Aruandlus', en: 'Reporting' },
  'sim.tl_cloud_outage_regulatory_desc': { et: 'L\u00f5pparuanne regulaatorile. V\u00e4ljumisstrateegiate \u00fclevaatamine.', en: 'Final report to regulator. Review of exit strategies.' },

  // Timeline events - Data breach
  'sim.tl_data_breach_detection': { et: 'Lekke avastamine', en: 'Breach Discovery' },
  'sim.tl_data_breach_detection_desc': { et: 'Andmeleke avastatakse (v\u00f5i kolmas osapool teavitab).', en: 'Data breach discovered (or third party reports it).' },
  'sim.tl_data_breach_containment': { et: 'Lekke piiramine', en: 'Breach Containment' },
  'sim.tl_data_breach_containment_desc': { et: 'Juurdep\u00e4\u00e4su sulgemine. Lekkinud andmete ulatuse hindamine.', en: 'Access revoked. Assessment of exposed data scope.' },
  'sim.tl_data_breach_notification': { et: 'GDPR + DORA teavitus', en: 'GDPR + DORA Notification' },
  'sim.tl_data_breach_notification_desc': { et: '72h GDPR teavitus + DORA Art. 19 kohaselt regulaatori teavitamine.', en: '72h GDPR notification + DORA Art. 19 regulator notification.' },
  'sim.tl_data_breach_investigation': { et: 'Forenseeriline uurimine', en: 'Forensic Investigation' },
  'sim.tl_data_breach_investigation_desc': { et: 'Lekke p\u00f5hjuse v\u00e4ljaselgitamine. Ohustatud kirjete arvu m\u00e4\u00e4ramine.', en: 'Root cause analysis. Determination of affected record count.' },
  'sim.tl_data_breach_recovery': { et: 'Klientide teavitamine', en: 'Client Communication' },
  'sim.tl_data_breach_recovery_desc': { et: 'Individuaalsed teavitused m\u00f5jutatud klientidele. Kreediitmonitooringute pakkumine.', en: 'Individual notifications to affected clients. Credit monitoring offers.' },
  'sim.tl_data_breach_regulatory': { et: 'Mitmekordne audit', en: 'Multiple Audits' },
  'sim.tl_data_breach_regulatory_desc': { et: 'Finantsinspektsiooni DORA audit + Andmekaitse Inspektsiooni GDPR audit.', en: 'Finantsinspektsioon DORA audit + Data Protection Authority GDPR audit.' },

  // Timeline events - Supply chain
  'sim.tl_supply_chain_detection': { et: 'Kompromissi avastamine', en: 'Compromise Discovery' },
  'sim.tl_supply_chain_detection_desc': { et: 'Kahtlane tegevus tuvastatud kolmanda osapoole tarkvara kaudu.', en: 'Suspicious activity detected through third-party software.' },
  'sim.tl_supply_chain_containment': { et: 'Isolatsiooni faas', en: 'Isolation Phase' },
  'sim.tl_supply_chain_containment_desc': { et: 'Kompromiteeritud tarkvara keelamine. Ohuhinnang.', en: 'Compromised software blocked. Threat assessment.' },
  'sim.tl_supply_chain_notification': { et: 'Sektori teavitamine', en: 'Sector Notification' },
  'sim.tl_supply_chain_notification_desc': { et: 'DORA Art. 19 aruandlus. Sektori\u00fclene hoiatuse edastamine.', en: 'DORA Art. 19 reporting. Cross-sector warning dissemination.' },
  'sim.tl_supply_chain_investigation': { et: 'Tarneahela audit', en: 'Supply Chain Audit' },
  'sim.tl_supply_chain_investigation_desc': { et: 'K\u00f5ikide kolmandate osapoolte allhankijate kontrollimine.', en: 'Review of all third-party subcontractors.' },
  'sim.tl_supply_chain_recovery': { et: 'Alternatiivide rakendamine', en: 'Alternative Implementation' },
  'sim.tl_supply_chain_recovery_desc': { et: 'Asendus- v\u00f5i parandatud tarkvara paigaldamine.', en: 'Replacement or patched software deployment.' },
  'sim.tl_supply_chain_regulatory': { et: 'V\u00e4ljumisstrateegia hindamine', en: 'Exit Strategy Review' },
  'sim.tl_supply_chain_regulatory_desc': { et: 'Regulaator hindab teie teenusepakkujate haldust ja v\u00e4ljumisplaane.', en: 'Regulator evaluates your vendor management and exit plans.' },

  // Timeline events - Insider threat
  'sim.tl_insider_threat_detection': { et: 'Kahtlase tegevuse tuvastamine', en: 'Suspicious Activity Detection' },
  'sim.tl_insider_threat_detection_desc': { et: 'Endise t\u00f6\u00f6taja volitamata juurdep\u00e4\u00e4s tuvastatud logidest.', en: 'Former employee unauthorized access detected from logs.' },
  'sim.tl_insider_threat_containment': { et: 'Juurdep\u00e4\u00e4su t\u00fchimine', en: 'Access Revocation' },
  'sim.tl_insider_threat_containment_desc': { et: 'K\u00f5ik seotud kontod suletakse. Parem\u00f5iguste audit.', en: 'All related accounts closed. Privilege audit.' },
  'sim.tl_insider_threat_notification': { et: 'Sisemine teavitamine', en: 'Internal Notification' },
  'sim.tl_insider_threat_notification_desc': { et: 'Juhtkond, \u00f5igusosakond ja vajadusel regulaator teavitatakse.', en: 'Management, legal, and if necessary regulator notified.' },
  'sim.tl_insider_threat_investigation': { et: 'Siseuurimine', en: 'Internal Investigation' },
  'sim.tl_insider_threat_investigation_desc': { et: 'Andmetele juurdep\u00e4\u00e4su logide anal\u00fc\u00fcs. Lekkinud andmete hindamine.', en: 'Data access log analysis. Assessment of exposed data.' },
  'sim.tl_insider_threat_recovery': { et: 'Turvameetmete t\u00e4iustamine', en: 'Security Enhancement' },
  'sim.tl_insider_threat_recovery_desc': { et: 'Juurdep\u00e4\u00e4su halduse \u00fclevaatamine. MFA rakendamine.', en: 'Access management review. MFA implementation.' },
  'sim.tl_insider_threat_regulatory': { et: 'Vastavuse kontroll', en: 'Compliance Review' },
  'sim.tl_insider_threat_regulatory_desc': { et: 'Siseauditi aruanne ja regulaatorile esitamine vajadusel.', en: 'Internal audit report and submission to regulator if needed.' },

  // Timeline events - API attack
  'sim.tl_api_attack_detection': { et: 'R\u00fcnnaku tuvastamine', en: 'Attack Detection' },
  'sim.tl_api_attack_detection_desc': { et: 'Anomaalne API liiklus tuvastatud. Massiline andmep\u00e4ring.', en: 'Anomalous API traffic detected. Mass data query.' },
  'sim.tl_api_attack_containment': { et: 'API piiramine', en: 'API Throttling' },
  'sim.tl_api_attack_containment_desc': { et: 'Haavatava endpointi sulgemine. Rate limiting rakendamine.', en: 'Vulnerable endpoint closed. Rate limiting applied.' },
  'sim.tl_api_attack_notification': { et: 'Intsidendi teavitus', en: 'Incident Notification' },
  'sim.tl_api_attack_notification_desc': { et: 'Regulaatori ja m\u00f5jutatud klientide teavitamine.', en: 'Regulator and affected clients notified.' },
  'sim.tl_api_attack_investigation': { et: 'Haavatavuse anal\u00fc\u00fcs', en: 'Vulnerability Analysis' },
  'sim.tl_api_attack_investigation_desc': { et: 'API turvaaugu p\u00f5hjuse ja andmelekke ulatuse anal\u00fc\u00fcs.', en: 'API vulnerability root cause and data exposure scope analysis.' },
  'sim.tl_api_attack_recovery': { et: 'Turvap\u00e4\u00e4su parandamine', en: 'Security Patching' },
  'sim.tl_api_attack_recovery_desc': { et: 'API haavatavuse parandamine. Turvatestimine enne taask\u00e4ivitamist.', en: 'API vulnerability fix. Security testing before relaunch.' },
  'sim.tl_api_attack_regulatory': { et: 'L\u00f5pparuanne', en: 'Final Report' },
  'sim.tl_api_attack_regulatory_desc': { et: 'Kogu intsident dokumenteeritud. Regulaatorile l\u00f5pparuande esitamine.', en: 'Full incident documented. Final report submitted to regulator.' },

  // Auth
  'auth.login': { et: 'Logi sisse', en: 'Log In' },
  'auth.register': { et: 'Registreeru', en: 'Register' },
  'auth.logout': { et: 'Logi v\u00e4lja', en: 'Log Out' },
  'auth.login_btn': { et: 'Sisene', en: 'Sign In' },
  'auth.register_btn': { et: 'Registreeru', en: 'Sign Up' },
  'auth.email': { et: 'E-post', en: 'Email' },
  'auth.password': { et: 'Parool', en: 'Password' },
  'auth.confirm_password': { et: 'Kinnita parool', en: 'Confirm Password' },
  'auth.full_name': { et: 'T\u00e4isnimi', en: 'Full Name' },
  'auth.no_account': { et: 'Pole kontot?', en: "Don't have an account?" },
  'auth.have_account': { et: 'On juba konto?', en: 'Already have an account?' },
  'auth.register_link': { et: 'Registreeru siin', en: 'Register here' },
  'auth.login_link': { et: 'Logi sisse siin', en: 'Log in here' },
  'auth.error_invalid': { et: 'Vale e-post v\u00f5i parool', en: 'Invalid email or password' },
  'auth.error_exists': { et: 'See e-post on juba registreeritud', en: 'This email is already registered' },
  'auth.error_mismatch': { et: 'Paroolid ei kattu', en: 'Passwords do not match' },

  // Footer
  'footer.built_for': { et: 'Loodud Eesti finantssektori ettev\u00f5tetele', en: 'Built for Estonian financial sector companies' },
  'footer.regulation': { et: 'Digitaalse tegevuskerksuse m\u00e4\u00e4rus', en: 'Digital Operational Resilience Act' },

  // Negotiations
  'nav.negotiations': { et: 'L\u00e4bir\u00e4\u00e4kimised', en: 'Negotiations' },
  'neg.title': { et: 'L\u00e4bir\u00e4\u00e4kimised', en: 'Negotiations' },
  'neg.empty': { et: 'L\u00e4bir\u00e4\u00e4kimisi pole veel alustatud.', en: 'No negotiations started yet.' },
  'neg.start': { et: 'Alusta l\u00e4bir\u00e4\u00e4kimist', en: 'Start Negotiation' },
  'neg.vendor_type': { et: 'Teenusepakkuja t\u00fc\u00fcp', en: 'Vendor Type' },
  'neg.vendor_cloud': { et: 'Pilveteenus', en: 'Cloud Service' },
  'neg.vendor_saas': { et: 'SaaS', en: 'SaaS' },
  'neg.vendor_outsourcing': { et: 'Allhange', en: 'Outsourcing' },
  'neg.vendor_hosting': { et: 'Majutus', en: 'Hosting' },
  'neg.vendor_other': { et: 'Muu', en: 'Other' },
  'neg.strategy': { et: 'Strateegia', en: 'Strategy' },
  'neg.generate_strategy': { et: 'Genereeri AI strateegia', en: 'Generate AI Strategy' },
  'neg.generate_email': { et: 'Genereeri e-kiri', en: 'Generate Email' },
  'neg.generating': { et: 'Genereerimine...', en: 'Generating...' },
  'neg.email_draft': { et: 'E-kirja mustand', en: 'Email Draft' },
  'neg.copy': { et: 'Kopeeri', en: 'Copy' },
  'neg.copied': { et: 'Kopeeritud!', en: 'Copied!' },
  'neg.items': { et: 'L\u00e4bir\u00e4\u00e4kimispunktid', en: 'Negotiation Items' },
  'neg.status_pending': { et: 'Ootel', en: 'Pending' },
  'neg.status_drafted': { et: 'Mustand', en: 'Drafted' },
  'neg.status_sent': { et: 'Saadetud', en: 'Sent' },
  'neg.status_responded': { et: 'Vastatud', en: 'Responded' },
  'neg.status_agreed': { et: 'Kokku lepitud', en: 'Agreed' },
  'neg.status_rejected': { et: 'Tagasi l\u00fckatud', en: 'Rejected' },
  'neg.overall_draft': { et: 'Mustand', en: 'Draft' },
  'neg.overall_in_progress': { et: 'K\u00e4imas', en: 'In Progress' },
  'neg.overall_completed': { et: 'L\u00f5petatud', en: 'Completed' },
  'neg.overall_stalled': { et: 'Peatunud', en: 'Stalled' },
  'neg.progress': { et: 'Edenemine', en: 'Progress' },
  'neg.suggested_clause': { et: 'Pakutav klausel', en: 'Suggested Clause' },
  'neg.legal_basis': { et: '\u00d5iguslik alus', en: 'Legal Basis' },
  'neg.back': { et: 'Tagasi nimekirja', en: 'Back to list' },

  // Guardian
  'nav.guardian': { et: 'Lepinguvalvur', en: 'Contract Guardian' },
  'guardian.title': { et: 'Lepinguvalvur', en: 'Contract Guardian' },
  'guardian.subtitle': { et: 'Pidev lepingute monitooring regulatiivsete muudatuste vastu.', en: 'Continuous contract monitoring against regulatory changes.' },
  'guardian.empty': { et: 'Seiratavaid lepinguid pole. Alustage lepingu anal\u00fc\u00fcsist.', en: 'No monitored contracts. Start with a contract analysis.' },
  'guardian.start_monitoring': { et: 'Alusta seiret', en: 'Start Monitoring' },
  'guardian.monitoring_started': { et: 'Seire alustatud!', en: 'Monitoring started!' },
  'guardian.status_active': { et: 'Aktiivne', en: 'Active' },
  'guardian.status_paused': { et: 'Peatatud', en: 'Paused' },
  'guardian.status_archived': { et: 'Arhiveeritud', en: 'Archived' },
  'guardian.pause': { et: 'Peata', en: 'Pause' },
  'guardian.resume': { et: 'J\u00e4tka', en: 'Resume' },
  'guardian.reanalyze': { et: 'Anal\u00fc\u00fcsi uuesti', en: 'Re-analyze' },
  'guardian.reanalyzing': { et: 'Anal\u00fc\u00fcsimine...', en: 'Analyzing...' },
  'guardian.last_analysis': { et: 'Viimane anal\u00fc\u00fcs', en: 'Last analysis' },
  'guardian.score': { et: 'Skoor', en: 'Score' },
  'guardian.alerts_title': { et: 'Teavitused', en: 'Alerts' },
  'guardian.alerts_empty': { et: 'Teavitusi pole.', en: 'No alerts.' },
  'guardian.mark_read': { et: 'M\u00e4rgi loetuks', en: 'Mark as read' },
  'guardian.unread': { et: 'Lugemata', en: 'Unread' },
  'guardian.all_alerts': { et: 'K\u00f5ik teavitused', en: 'All alerts' },
  'guardian.severity_high': { et: 'K\u00f5rge', en: 'High' },
  'guardian.severity_medium': { et: 'Keskmine', en: 'Medium' },
  'guardian.severity_low': { et: 'Madal', en: 'Low' },
  'guardian.reg_updates': { et: 'Regulatiivsed uuendused', en: 'Regulatory Updates' },
  'guardian.reg_empty': { et: 'Regulatiivseid uuendusi pole.', en: 'No regulatory updates.' },
  'guardian.reg_source': { et: 'Allikas', en: 'Source' },
  'guardian.reg_relevance': { et: 'Olulisus', en: 'Relevance' },
  'guardian.reg_affected': { et: 'M\u00f5jutatud artiklid', en: 'Affected articles' },
  'guardian.view_analysis': { et: 'Vaata anal\u00fc\u00fcsi', en: 'View analysis' },
  'guardian.back': { et: 'Tagasi valvurisse', en: 'Back to Guardian' },
};

@Injectable({ providedIn: 'root' })
export class LangService {
  private langSignal = signal<Lang>((localStorage.getItem('dora_lang') as Lang) || 'et');

  lang = this.langSignal.asReadonly();

  get currentLang(): Lang {
    return this.langSignal();
  }

  toggle() {
    const next: Lang = this.langSignal() === 'et' ? 'en' : 'et';
    this.langSignal.set(next);
    localStorage.setItem('dora_lang', next);
  }

  t(key: string): string {
    const entry = TRANSLATIONS[key];
    if (!entry) return key;
    return entry[this.langSignal()] || entry['et'] || key;
  }
}
