import { Injectable, signal, computed } from '@angular/core';

export type Lang = 'et' | 'en';

const TRANSLATIONS: { [key: string]: { et: string; en: string } } = {
  // Nav
  'nav.history': { et: 'Ajalugu', en: 'History' },
  'nav.assessment': { et: 'Hindamine', en: 'Assessment' },
  'nav.subtitle': { et: 'IKT-lepingute hindamine', en: 'ICT Contract Assessment' },
  'nav.methodology': { et: 'Metoodika', en: 'Methodology' },
  'nav.brand': { et: 'DORA Art. 30', en: 'DORA Art. 30' },

  // Methodology
  'methodology.title': { et: 'Hindamise metoodika', en: 'Assessment Methodology' },
  'methodology.subtitle': { et: 'Kuidas me hindame IKT-lepingute vastavust DORA artikkel 30 n\u00f5uetele', en: 'How we assess ICT contract compliance with DORA Article 30 requirements' },
  'methodology.art30_title': { et: 'DORA artikkel 30 n\u00f5uded', en: 'DORA Article 30 Requirements' },
  'methodology.art30_desc': { et: 'DORA artikkel 30 s\u00e4testab kohustuslikud elemendid, mis peavad sisalduma finantssektori ettev\u00f5tete ja IKT-teenusepakkujate vahelistes lepingutes.', en: 'DORA Article 30 establishes mandatory elements that must be included in contracts between financial sector entities and ICT service providers.' },
  'methodology.req_sla': { et: 'Teenustaseme kokkulepped', en: 'Service Level Agreements' },
  'methodology.req_sla_desc': { et: 'Konkreetsed ja m\u00f5\u00f5detavad teenustasemed k\u00e4ttesaadavuse, j\u00f5udluse ja toe kohta', en: 'Specific and measurable service levels for availability, performance and support' },
  'methodology.req_exit': { et: 'V\u00e4ljumisstrateegia', en: 'Exit Strategy' },
  'methodology.req_exit_desc': { et: 'Selged tingimused lepingu l\u00f5petamiseks ja andmete \u00fclekandmiseks', en: 'Clear terms for contract termination and data migration' },
  'methodology.req_audit': { et: 'Auditi \u00f5igused', en: 'Audit Rights' },
  'methodology.req_audit_desc': { et: 'Juurdepe\u00e4\u00e4s auditiks ja IKT-s\u00fcsteemide kontrollimiseks', en: 'Access for auditing and inspection of ICT systems' },
  'methodology.req_incident': { et: 'Intsidentidest teatamine', en: 'Incident Reporting' },
  'methodology.req_incident_desc': { et: 'Kohustus teatada IKT-intsidentidest ja nende m\u00f5just', en: 'Obligation to report ICT incidents and their impact' },
  'methodology.req_data': { et: 'Andmekaitse', en: 'Data Protection' },
  'methodology.req_data_desc': { et: 'Andmete asukoha ja t\u00f6\u00f6tlemise tingimused', en: 'Data location and processing conditions' },
  'methodology.req_subcontracting': { et: 'Allhange', en: 'Subcontracting' },
  'methodology.req_subcontracting_desc': { et: 'Tingimused allhanke kasutamiseks ja teatamiseks', en: 'Terms for using and notifying about subcontractors' },
  'methodology.req_location': { et: 'Asukohaan\u00f5uded', en: 'Location Requirements' },
  'methodology.req_location_desc': { et: 'Teenuse osutamise ja andmete t\u00f6\u00f6tlemise asukohad', en: 'Service provision and data processing locations' },
  'methodology.req_termination': { et: 'L\u00f5petamistingimused', en: 'Termination Terms' },
  'methodology.req_termination_desc': { et: 'Lepingu l\u00f5petamise p\u00f5hjused ja protseduurid', en: 'Grounds and procedures for contract termination' },
  'methodology.process_title': { et: 'Hindamisprotsess', en: 'Assessment Process' },
  'methodology.step1_title': { et: 'Lepingu \u00fcleslaadimine', en: 'Contract Upload' },
  'methodology.step1_desc': { et: 'Laadige \u00fcles oma IKT-leping PDF v\u00f5i DOCX formaadis. Fail t\u00f6\u00f6deldakse turvaliselt.', en: 'Upload your ICT contract in PDF or DOCX format. The file is processed securely.' },
  'methodology.step2_title': { et: 'Automaatne anal\u00fc\u00fcs', en: 'Automated Analysis' },
  'methodology.step2_desc': { et: 'S\u00fcsteem anal\u00fc\u00fcsib lepingut k\u00f5igi DORA Art. 30 n\u00f5uete vastu, otsides vastavaid klausleid.', en: 'The system analyzes the contract against all DORA Art. 30 requirements, searching for matching clauses.' },
  'methodology.step3_title': { et: 'Tulemuste genereerimine', en: 'Results Generation' },
  'methodology.step3_desc': { et: 'Saate detailse aruande leitud, osaliselt leitud ja puuduvate klauslite kohta koos soovitustega.', en: 'You receive a detailed report of found, partially found, and missing clauses with recommendations.' },
  'methodology.step4_title': { et: 'Soovituslikud klauslid', en: 'Suggested Clauses' },
  'methodology.step4_desc': { et: 'Puuduvate n\u00f5uete jaoks pakume v\u00e4lja soovituslikud lepinguklauslid, mida saate kasutada.', en: 'For missing requirements, we provide suggested contract clauses that you can use.' },
  'methodology.scoring_title': { et: 'Skoori arvutamine', en: 'Scoring Methodology' },
  'methodology.scoring_desc': { et: 'Vastavusskoor arvutatakse leitud n\u00f5uete p\u00f5hjal. Osaliselt leitud n\u00f5uded annavad pool punkti.', en: 'The compliance score is calculated based on found requirements. Partially found requirements give half points.' },
  'methodology.compliant': { et: 'Vastav', en: 'Compliant' },
  'methodology.partial': { et: 'Osaliselt vastav', en: 'Partially Compliant' },
  'methodology.non_compliant': { et: 'Mittevastav', en: 'Non-Compliant' },
  'methodology.references_title': { et: 'Regulatiivsed viited', en: 'Regulatory References' },
  'methodology.start_assessment': { et: 'Alusta hindamist', en: 'Start Assessment' },

  // Landing - Hero
  'landing.subtitle': { et: 'Lepingu eelkontroll', en: 'Contract Pre-Check' },
  'landing.hero_desc': { et: 'Kontrollige oma IKT-lepingute vastavust DORA artikkel 30 n\u00f5uetele enne auditit.', en: 'Check your ICT contract compliance with DORA Article 30 requirements before audit.' },
  'landing.cta_try_sample': { et: 'Proovi n\u00e4idislepinguga', en: 'Try with sample contract' },
  'landing.cta_generate': { et: 'Genereeri leping', en: 'Generate Contract' },
  'landing.cta_assessment': { et: 'Enesehindamine', en: 'Self-assessment' },
  'landing.cta_check': { et: 'Kontrolli lepingut', en: 'Check contract' },

  // Landing - Stats
  'landing.stat_requirements': { et: 'kontrollitavat n\u00f5uet', en: 'requirements checked' },
  'landing.stat_time': { et: 'kontrolli aeg', en: 'check time' },
  'landing.stat_report': { et: 'aruanne', en: 'report' },

  // Landing - Steps
  'landing.steps_title': { et: 'Kuidas see t\u00f6\u00f6tab', en: 'How it works' },
  'landing.step1_title': { et: 'Laadige leping \u00fcles', en: 'Upload contract' },
  'landing.step1_desc': { et: 'PDF v\u00f5i DOCX, kuni 10 MB', en: 'PDF or DOCX, up to 10 MB' },
  'landing.step2_title': { et: 'S\u00fcsteem kontrollib', en: 'System checks' },
  'landing.step2_desc': { et: 'Kontroll DORA Art. 30 n\u00f5uete vastu', en: 'Check against DORA Art. 30 requirements' },
  'landing.step3_title': { et: 'Saate aruande', en: 'Get report' },
  'landing.step3_desc': { et: 'Puudused ja soovitused PDF-ina', en: 'Gaps and recommendations as PDF' },

  // Landing - Scope
  'landing.scope_title': { et: 'Mida see t\u00f6\u00f6riist teeb ja ei tee', en: 'What this tool does and does not do' },
  'landing.scope_does': { et: 'Teeb:', en: 'Does:' },
  'landing.scope_does_1': { et: 'Kontrollib lepingut 8 DORA Art. 30 n\u00f5ude vastu', en: 'Checks contract against 8 DORA Art. 30 requirements' },
  'landing.scope_does_2': { et: 'N\u00e4itab puuduvad ja osaliselt kaetud klauslid', en: 'Shows missing and partially covered clauses' },
  'landing.scope_does_3': { et: 'Pakub soovituslikke klausleid', en: 'Suggests template clauses' },
  'landing.scope_not': { et: 'Ei tee:', en: 'Does not:' },
  'landing.scope_not_1': { et: 'Ei asenda juriidilist n\u00f5ustamist', en: 'Does not replace legal advice' },
  'landing.scope_not_2': { et: 'Ei garanteeri vastavust', en: 'Does not guarantee compliance' },
  'landing.scope_not_3': { et: 'Ei muuda lepingut automaatselt', en: 'Does not auto-modify contracts' },

  // Landing - Final CTA
  'landing.final_cta_title': { et: 'Kontrollige oma lepingut', en: 'Check your contract' },
  'landing.final_cta_desc': { et: 'Saate teada, millised DORA Art. 30 n\u00f5uded on kaetud ja millised vajavad t\u00e4iendamist.', en: 'Find out which DORA Art. 30 requirements are covered and which need attention.' },

  // Footer
  'footer.disclaimer': { et: 'Eelkontroll, mitte juriidiline n\u00f5ustamine', en: 'Pre-check, not legal advice' },

  // Landing - Who needs this
  'landing.who_label': { et: 'Kohustuslik vastavus', en: 'Mandatory compliance' },
  'landing.who_title': { et: 'Kellele DORA kehtib?', en: 'Who must comply with DORA?' },
  'landing.who_subtitle': { et: 'Finantsinspektsiooni j\u00e4relevalve all olevad ettev\u00f5tted ja nende IKT-teenusepakkujad', en: 'Companies under Finantsinspektsioon oversight and their ICT service providers' },

  // Sectors
  'landing.sector_banks': { et: 'Pangad', en: 'Banks' },
  'landing.sector_banks_ex': { et: 'LHV, Coop, Bigbank jt', en: 'LHV, Coop, Bigbank etc.' },
  'landing.sector_banks_pain': { et: 'Sajad IKT-lepingud vajavad \u00fclevaatamist DORA Art. 30 n\u00f5uetele', en: 'Hundreds of ICT contracts need review against DORA Art. 30' },
  'landing.sector_insurance': { et: 'Kindlustus', en: 'Insurance' },
  'landing.sector_insurance_ex': { et: 'ERGO, If, Salva jt', en: 'ERGO, If, Salva etc.' },
  'landing.sector_insurance_pain': { et: 'Kolmandate osapoolte riskide haldamine ja lepingute vastavus', en: 'Third-party risk management and contract compliance' },
  'landing.sector_payments': { et: 'Makselahendused', en: 'Payment Services' },
  'landing.sector_payments_ex': { et: 'Wise, Montonio, EveryPay jt', en: 'Wise, Montonio, EveryPay etc.' },
  'landing.sector_payments_pain': { et: 'Kriitiliste pilveteenuste lepingud peavad vastama DORA n\u00f5uetele', en: 'Critical cloud service contracts must meet DORA requirements' },
  'landing.sector_crypto': { et: 'Kr\u00fcptovara', en: 'Crypto Assets' },
  'landing.sector_crypto_ex': { et: 'Litsentseeritud teenusepakkujad', en: 'Licensed service providers' },
  'landing.sector_crypto_pain': { et: 'Uus regulatiivne kohustus \u2014 vastavus tuleb tagada kiiresti', en: 'New regulatory obligation \u2014 compliance must be ensured quickly' },
  'landing.sector_funds': { et: 'Fondivalitsejad', en: 'Fund Managers' },
  'landing.sector_funds_ex': { et: 'Investeerimis\u00fchingud', en: 'Investment firms' },
  'landing.sector_funds_pain': { et: 'Varahalduse IKT-s\u00f5ltuvuste kaardistamine ja lepingute audit', en: 'Mapping ICT dependencies and auditing contracts in asset management' },
  'landing.sector_ict': { et: 'IKT-teenusepakkujad', en: 'ICT Service Providers' },
  'landing.sector_ict_ex': { et: 'IT-ettev\u00f5tted, pilveteenused', en: 'IT companies, cloud services' },
  'landing.sector_ict_pain': { et: 'Teie kliendid n\u00f5uavad DORA-vastavust \u2014 lepingud peavad vastama', en: 'Your clients demand DORA compliance \u2014 contracts must comply' },

  // Landing - Features
  'landing.features_label': { et: 'Platvormi v\u00f5imalused', en: 'Platform Features' },
  'landing.features_title': { et: 'K\u00f5ik, mida vajate DORA vastavuseks', en: 'Everything you need for DORA compliance' },
  'landing.feat_ai_title': { et: 'Automaatne lepinguaudit', en: 'Automated Contract Audit' },
  'landing.feat_ai_desc': { et: 'Laadige \u00fcles PDF/DOCX ja saage kohene anal\u00fc\u00fcs DORA Art. 30 vastu.', en: 'Upload PDF/DOCX and get instant analysis against DORA Art. 30.' },
  'landing.feat_fast_title': { et: 'Kiire hindamine', en: 'Quick Assessment' },
  'landing.feat_fast_desc': { et: '37 k\u00fcsimust, tulemused koheselt. Valmis 5 minutiga.', en: '37 questions, instant results. Done in 5 minutes.' },
  'landing.feat_radar_title': { et: 'Radardiagramm', en: 'Radar Chart' },
  'landing.feat_radar_desc': { et: 'Visuaalne vastavusprofiil 15 kategooria l\u00f5ikes.', en: 'Visual compliance profile across 15 categories.' },
  'landing.feat_risk_title': { et: 'Riskimaatriks', en: 'Risk Matrix' },
  'landing.feat_risk_desc': { et: 'Likelihood vs Impact 3x3 heatmap riskide visualiseerimiseks.', en: 'Likelihood vs Impact 3x3 heatmap for risk visualization.' },
  'landing.feat_pdf_title': { et: 'PDF aruanne', en: 'PDF Report' },
  'landing.feat_pdf_desc': { et: 'Professionaalne aruanne printimisel v\u00f5i PDF ekspordiks.', en: 'Professional report for printing or PDF export.' },
  'landing.feat_cert_title': { et: 'Vastavustunnistus', en: 'Compliance Certificate' },
  'landing.feat_cert_desc': { et: 'Sertifikaat ettev\u00f5tte vastavustaseme kinnitamiseks.', en: 'Certificate confirming company compliance level.' },


  // Landing - Pillars
  'landing.pillars_label': { et: 'DORA raamistik', en: 'DORA Framework' },
  'landing.pillars_title': { et: '5 sammast', en: '5 Pillars' },
  'landing.pillars_desc': { et: 'Digitaalse tegevuskerksuse m\u00e4\u00e4ruse viis p\u00f5hisammast', en: 'Five core pillars of the Digital Operational Resilience Act' },
  'landing.pillar_risk': { et: 'IKT riskihaldus', en: 'ICT Risk Management' },
  'landing.pillar_incident': { et: 'Intsidendid', en: 'Incidents' },
  'landing.pillar_testing': { et: 'Testimine', en: 'Testing' },
  'landing.pillar_thirdparty': { et: 'Kolmandad osapooled', en: 'Third Parties' },
  'landing.pillar_info': { et: 'Info jagamine', en: 'Information Sharing' },
  'landing.active': { et: 'Aktiivne', en: 'Active' },
  'landing.soon': { et: 'Peagi', en: 'Soon' },
  'landing.categories': { et: 'Hindamise valdkonnad', en: 'Assessment Areas' },
  'landing.pillars': { et: 'DORA 5 sammast', en: 'DORA 5 Pillars' },

  // Landing - Category badges
  'landing.cat_service': { et: 'Teenustase', en: 'Service Level' },
  'landing.cat_exit': { et: 'V\u00e4ljumisstrateegia', en: 'Exit Strategy' },
  'landing.cat_audit': { et: 'Audit', en: 'Audit' },
  'landing.cat_incident': { et: 'Intsidendid', en: 'Incidents' },
  'landing.cat_data': { et: 'Andmekaitse', en: 'Data Protection' },
  'landing.cat_subcontracting': { et: 'Allhange', en: 'Subcontracting' },
  'landing.cat_risk': { et: 'Risk', en: 'Risk' },
  'landing.cat_legal': { et: '\u00d5igus', en: 'Legal' },
  'landing.cat_continuity': { et: 'Pidevus', en: 'Continuity' },
  'landing.cat_recruitment': { et: 'V\u00e4rbamine', en: 'Recruitment' },
  'landing.cat_financial': { et: 'Finantsaruandlus', en: 'Financial Reporting' },
  'landing.cat_ict_risk': { et: 'IKT riskihaldus', en: 'ICT Risk Management' },
  'landing.cat_incident_ext': { et: 'Intsidendid (laiendatud)', en: 'Incidents (Extended)' },
  'landing.cat_testing': { et: 'Testimine', en: 'Testing' },
  'landing.cat_info': { et: 'Info jagamine', en: 'Information Sharing' },

  // Landing - Timeline
  'landing.timeline_label': { et: 'Regulatsiooni ajajoon', en: 'Regulation Timeline' },
  'landing.timeline_title': { et: 'DORA t\u00e4htp\u00e4evad', en: 'DORA Milestones' },
  'landing.tl_proposal_title': { et: 'DORA ettepanek', en: 'DORA Proposal' },
  'landing.tl_proposal_desc': { et: 'Euroopa Komisjon avaldab DORA m\u00e4\u00e4ruse ettepaneku', en: 'European Commission publishes DORA regulation proposal' },
  'landing.tl_adoption_title': { et: 'DORA vastuv\u00f5tmine', en: 'DORA Adoption' },
  'landing.tl_adoption_desc': { et: 'Euroopa Parlament kiidab m\u00e4\u00e4ruse heaks', en: 'European Parliament approves the regulation' },
  'landing.tl_force_title': { et: 'J\u00f5ustumine', en: 'Entry into Force' },
  'landing.tl_force_desc': { et: 'DORA m\u00e4\u00e4rus j\u00f5ustub ametlikult', en: 'DORA regulation officially enters into force' },
  'landing.tl_apply_title': { et: 'Kohaldamine', en: 'Application' },
  'landing.tl_apply_desc': { et: 'T\u00e4ielik kohaldamine k\u00f5igile finantssektori ettev\u00f5tetele', en: 'Full application to all financial sector companies' },
  'landing.tl_enforce_title': { et: 'Aktiivne j\u00e4relevalve', en: 'Active Enforcement' },
  'landing.tl_enforce_desc': { et: 'Finantsinspektsioon alustab s\u00fcsteemset DORA auditit. Trahvid kuni 2% k\u00e4ibest.', en: 'Finantsinspektsioon begins systematic DORA audits. Fines up to 2% of turnover.' },

  // Landing - Marquee
  'landing.marquee_label': { et: 'Sobib igale finantssektori ettev\u00f5ttele', en: 'Suitable for all financial sector companies' },
  'landing.m_banks': { et: 'Pangad', en: 'Banks' },
  'landing.m_payments': { et: 'Makseasutused', en: 'Payment Institutions' },
  'landing.m_investment': { et: 'Investeerimis\u00fchingud', en: 'Investment Firms' },
  'landing.m_insurance': { et: 'Kindlustusseltsid', en: 'Insurance Companies' },
  'landing.m_funds': { et: 'Fondivalitsejad', en: 'Fund Managers' },
  'landing.m_audit': { et: 'Auditifirmad', en: 'Audit Firms' },
  'landing.m_ict': { et: 'IKT-teenusepakkujad', en: 'ICT Providers' },
  'landing.m_cloud': { et: 'Pilveteenused', en: 'Cloud Services' },
  'landing.m_cyber': { et: 'K\u00fcberturbe ettev\u00f5tted', en: 'Cybersecurity Firms' },
  'landing.m_fintech': { et: 'Fintech startupid', en: 'Fintech Startups' },

  // Landing - Reviews
  'landing.reviews_label': { et: 'Tagasiside', en: 'Testimonials' },
  'landing.reviews_title': { et: 'Mida kliendid \u00fctlevad', en: 'What clients say' },

  // Landing - Contact
  'landing.contact_title': { et: 'V\u00f5ta meiega \u00fchendust', en: 'Get in touch' },
  'landing.contact_subtitle': { et: 'Saame sinuga 24h jooksul kontakti', en: 'We\u2019ll get back to you within 24h' },
  'landing.contact_btn': { et: 'Saada p\u00e4ring', en: 'Send inquiry' },
  'landing.contact_email_placeholder': { et: 'teie@ettevote.ee', en: 'your@company.com' },
  'landing.contact_success': { et: 'Täname! Võtame sinuga peagi ühendust.', en: 'Thank you! We will contact you soon.' },
  'landing.contact_error': { et: 'Palun sisestage kehtiv e-posti aadress', en: 'Please enter a valid email address' },

  // Landing - Stats (counter section)
  'landing.stat_contracts': { et: 'lepingut analüüsitud', en: 'contracts analyzed' },
  'landing.stat_orgs': { et: 'organisatsiooni kasutab', en: 'organizations using' },
  'landing.stat_satisfaction': { et: 'kasutaja rahul', en: 'user satisfaction' },

  // Landing - Pillars hints
  'landing.pillars_hint': { et: 'Kliki sambal, et näha detailseid nõudeid', en: 'Click on a pillar to see detailed requirements' },
  'landing.pillar_tooltip': { et: 'Kliki detailide nägemiseks', en: 'Click to see details' },

  // Landing - Upload preview
  'landing.upload_drag': { et: 'Lohista PDF v\u00f5i DOCX siia', en: 'Drag PDF or DOCX here' },
  'landing.upload_click': { et: 'V\u00f5i kliki faili valimiseks', en: 'Or click to select a file' },

  // Landing - Interactive table
  'landing.interactive_label': { et: 'Interaktiivne kontroll', en: 'Interactive check' },
  'landing.interactive_title': { et: 'DORA Art. 30 N\u00f5uded', en: 'DORA Art. 30 Requirements' },
  'landing.interactive_desc': { et: 'Kliki n\u00f5udel, et n\u00e4ha selgitust', en: 'Click on a requirement to see explanation' },
  'landing.table_check': { et: '\u2713', en: '\u2713' },
  'landing.table_requirement': { et: 'N\u00f5ue', en: 'Requirement' },
  'landing.table_status': { et: 'Staatus', en: 'Status' },
  'landing.table_ok': { et: 'OK', en: 'OK' },
  'landing.table_missing': { et: 'Puudu', en: 'Missing' },
  'landing.table_check_contract': { et: 'Kontrolli oma lepingut', en: 'Check your contract' },
  'landing.table_checked': { et: 'Kontrollitud', en: 'Checked' },
  'landing.review1_text': { et: 'AI lepinguaudit s\u00e4\u00e4stis meile n\u00e4dalaid konsultandi tasu. Saime kohe teada, millised klauslid puuduvad.', en: 'AI contract audit saved us weeks of consultant fees. We instantly knew which clauses were missing.' },
  'landing.review1_role': { et: 'IT-vastavusjuht, fintech-ettev\u00f5te', en: 'IT Compliance Manager, fintech company' },
  'landing.review2_text': { et: 'Radardiagramm annab suurep\u00e4rase \u00fclevaate. N\u00fc\u00fcd teame t\u00e4pselt, kus peame parandusi tegema.', en: 'Radar chart gives an excellent overview. Now we know exactly where improvements are needed.' },
  'landing.review2_role': { et: 'Riskijuht, kindlustusselts', en: 'Risk Manager, insurance company' },
  'landing.review3_text': { et: 'Kasutame seda regulaarselt k\u00f5igi oma IKT-lepingute kontrollimiseks. V\u00e4ga professionaalne.', en: 'We use it regularly to check all our ICT contracts. Very professional.' },
  'landing.review3_role': { et: 'IKT lepingute haldur, pank', en: 'ICT Contract Manager, bank' },

  // Landing - Trust
  'landing.trust_title': { et: 'Loodud Eesti finantssektorile', en: 'Built for Estonian Financial Sector' },
  'landing.trust_desc': { et: 'P\u00f5hineb DORA m\u00e4\u00e4rusel 2022/2554. Eestikeelne. Andmed ei lahku Euroopa Liidust.', en: 'Based on DORA regulation 2022/2554. In Estonian. Data stays within the EU.' },
  'landing.trust_eu_data': { et: 'Andmed EL-is', en: 'Data in EU' },
  'landing.trust_ai': { et: 'AI anal\u00fc\u00fcs', en: 'AI Analysis' },

  // Landing - EU compliance
  'landing.eu_compliance': { et: 'EU regulatsioonide vastavus', en: 'EU Regulatory Compliance' },
  'landing.eu_desc_dora': { et: 'Toetab', en: 'Supports' },
  'landing.eu_desc_nis2': { et: 'tugi on tulemas.', en: 'support coming soon.' },


  // Assessment
  'assessment.title': { et: 'DORA vastavuse hindamine', en: 'DORA Compliance Assessment' },
  'assessment.step_data': { et: 'Andmed', en: 'Data' },
  'assessment.step_questions': { et: 'K\u00fcsimused', en: 'Questions' },
  'assessment.step_results': { et: 'Tulemused', en: 'Results' },
  'assessment.company': { et: 'Ettev\u00f5tte andmed', en: 'Company Information' },
  'assessment.company_name': { et: 'Ettev\u00f5tte nimi', en: 'Company Name' },
  'assessment.contract_name': { et: 'Lepingu nimetus', en: 'Contract Name' },
  'assessment.submit': { et: 'Esita hindamine', en: 'Submit Assessment' },
  'assessment.submitting': { et: 'Hindamine...', en: 'Assessing...' },
  'assessment.score_preview': { et: 'Eeldatav skoor', en: 'Expected Score' },
  'assessment.yes': { et: 'Jah', en: 'Yes' },
  'assessment.no': { et: 'Ei', en: 'No' },
  'assessment.questions_suffix': { et: 'k\u00fcsimust', en: 'questions' },
  'assessment.question_suffix': { et: 'k\u00fcsimus', en: 'question' },
  'assessment.sector': { et: 'Sektor', en: 'Sector' },
  'assessment.select_sector': { et: 'Valige sektor...', en: 'Select sector...' },
  'assessment.scenario_ideal': { et: 'Ideaalne leping', en: 'Ideal contract' },
  'assessment.scenario_average': { et: 'Keskmine leping', en: 'Average contract' },
  'assessment.scenario_weak': { et: 'N\u00f5rk leping', en: 'Weak contract' },
  'assessment.clear': { et: 'T\u00fchjenda', en: 'Clear' },

  // Results
  'results.loading': { et: 'Tulemuste laadimine...', en: 'Loading results...' },
  'results.percent': { et: 'protsenti', en: 'percent' },
  'results.compliant': { et: 'vastav', en: 'compliant' },
  'results.non_compliant': { et: 'mittevastav', en: 'non-compliant' },
  'results.total': { et: 'kokku', en: 'total' },
  'results.profile': { et: 'Vastavuse profiil', en: 'Compliance Profile' },
  'results.risk_matrix': { et: 'Riskimaatriks', en: 'Risk Matrix' },
  'results.low': { et: 'Madal', en: 'Low' },
  'results.medium': { et: 'Keskmine', en: 'Medium' },
  'results.high': { et: 'K\u00f5rge', en: 'High' },
  'results.low_risk': { et: 'Madal risk', en: 'Low Risk' },
  'results.med_risk': { et: 'Keskmine', en: 'Medium' },
  'results.high_risk': { et: 'K\u00f5rge risk', en: 'High Risk' },
  'results.likelihood': { et: 'T\u00f5en\u00e4osus', en: 'Likelihood' },
  'results.impact': { et: 'M\u00f5ju', en: 'Impact' },
  'results.pillars': { et: 'DORA 5 sammast', en: 'DORA 5 Pillars' },
  'results.detail': { et: 'Detailne \u00fclevaade', en: 'Detailed Overview' },
  'results.recommendation': { et: 'Soovitus', en: 'Recommendation' },
  'results.priority': { et: 'Prioriteetne tegevuskava', en: 'Priority Action Plan' },
  'results.gaps': { et: 'puudust', en: 'gaps' },
  'results.critical': { et: 'Kriitiline', en: 'Critical' },
  'results.important': { et: 'Oluline', en: 'Important' },
  'results.download_pdf': { et: 'Laadi PDF', en: 'Download PDF' },
  'results.new_assessment': { et: 'Uus hindamine', en: 'New Assessment' },
  'results.history': { et: 'Ajalugu', en: 'History' },
  'results.green': { et: 'Vastav', en: 'Compliant' },
  'results.yellow': { et: 'Osaliselt vastav', en: 'Partially Compliant' },
  'results.red': { et: 'Mittevastav', en: 'Non-Compliant' },
  'results.certificate': { et: 'Tunnistus', en: 'Certificate' },
  'results.fine_risk': { et: 'Trahviriski hinnang', en: 'Fine Risk Estimate' },
  'results.fine_red': { et: 'K\u00f5rge risk \u2014 Finantsinspektsioon v\u00f5ib m\u00e4\u00e4rata trahvi kuni 2% aastasest k\u00e4ibest', en: 'High risk \u2014 Finantsinspektsioon may impose a fine up to 2% of annual turnover' },
  'results.fine_yellow': { et: 'Keskmine risk \u2014 Ettekirjutuse ja m\u00e4rkuste risk on olemas', en: 'Medium risk \u2014 Risk of prescriptions and remarks exists' },
  'results.fine_green': { et: 'Madal risk \u2014 Vastavus on tagatud, j\u00e4tkake regulaarset \u00fclevaatust', en: 'Low risk \u2014 Compliance is ensured, continue regular review' },
  'results.fine_note': { et: 'Hinnang p\u00f5hineb DORA m\u00e4\u00e4rusel 2022/2554 ja Finantsinspektsiooni j\u00e4relevalvepraktikal', en: 'Estimate based on DORA regulation 2022/2554 and Finantsinspektsioon supervisory practice' },
  'results.of_turnover': { et: 'k\u00e4ibest', en: 'of turnover' },
  'results.cta_contract_title': { et: 'Kontrollige ka oma IKT-lepinguid', en: 'Also check your ICT contracts' },
  'results.cta_contract_desc': { et: 'Automaatne anal\u00fc\u00fcs kontrollib lepingut DORA Art. 30 n\u00f5uete vastu ja annab soovitused puuduste k\u00f5rvaldamiseks', en: 'Automated analysis checks contracts against DORA Art. 30 requirements and provides recommendations for fixing gaps' },
  'results.cta_contract_btn': { et: 'Anal\u00fc\u00fcsi lepingut', en: 'Analyze contract' },

  // History
  'history.title': { et: 'Hindamiste ajalugu', en: 'Assessment History' },
  'history.total': { et: 'hindamist kokku', en: 'total assessments' },
  'history.avg_score': { et: 'Keskmine skoor', en: 'Average Score' },
  'history.compliant': { et: 'Vastavad', en: 'Compliant' },
  'history.partial': { et: 'Osaliselt', en: 'Partial' },
  'history.non_compliant': { et: 'Mittevastav', en: 'Non-Compliant' },
  'history.trend': { et: 'Skoori trend', en: 'Score Trend' },
  'history.empty_title': { et: 'Ajalugu on t\u00fchi', en: 'History is Empty' },
  'history.empty_desc': { et: 'Te pole veel \u00fchtegi hindamist l\u00e4bi viinud.', en: 'You haven\u2019t completed any assessments yet.' },
  'history.first': { et: 'Alusta esimest hindamist', en: 'Start First Assessment' },
  'history.clear': { et: 'Kustuta ajalugu', en: 'Clear History' },
  'history.new': { et: 'Uus hindamine', en: 'New Assessment' },

  // Contract Analysis
  'nav.contract': { et: 'Lepingu kontroll', en: 'Contract Check' },
  'contract.title': { et: 'Lepingu kontroll', en: 'Contract Check' },
  'contract.subtitle': { et: 'DORA Art. 30 n\u00f5uete kontroll', en: 'DORA Art. 30 requirements check' },
  'contract.upload_label': { et: 'Lae \u00fcles leping (PDF v\u00f5i DOCX)', en: 'Upload contract (PDF or DOCX)' },
  'contract.upload_hint': { et: 'Maksimaalselt 10 MB', en: 'Maximum 10 MB' },
  'contract.company_name': { et: 'Ettev\u00f5tte nimi', en: 'Company Name' },
  'contract.contract_name': { et: 'Lepingu nimetus', en: 'Contract Name' },
  'contract.analyze': { et: 'Kontrolli lepingut', en: 'Check Contract' },
  'contract.analyzing': { et: 'Kontrollin lepingut...', en: 'Checking contract...' },
  'contract.ai_note': { et: 'Kontrollime lepingut DORA Art. 30 n\u00f5uete vastu. See v\u00f5ib v\u00f5tta kuni 1 minut.', en: 'Checking the contract against DORA Art. 30 requirements. This may take up to 1 minute.' },
  'contract.results': { et: 'Kontrolli tulemused', en: 'Check Results' },
  'contract.score': { et: 'Vastavusskoor', en: 'Compliance Score' },
  'contract.found': { et: 'Leitud', en: 'Found' },
  'contract.missing': { et: 'Puudu', en: 'Missing' },
  'contract.partial': { et: 'Osaliselt', en: 'Partial' },
  'contract.quote': { et: 'Tsitaat lepingust', en: 'Quote from contract' },
  'contract.recommendation': { et: 'Soovitus', en: 'Recommendation' },
  'contract.new_analysis': { et: 'Uus kontroll', en: 'New Check' },
  'contract.drag_drop': { et: 'Lohista fail siia v\u00f5i kliki valimiseks', en: 'Drag file here or click to select' },
  'contract.file_selected': { et: 'Fail valitud', en: 'File selected' },
  'contract.error': { et: 'Anal\u00fc\u00fcs eba\u00f5nnestus. Palun proovige uuesti.', en: 'Analysis failed. Please try again.' },
  'contract.summary': { et: 'Kokkuv\u00f5te', en: 'Summary' },
  'contract.download_pdf': { et: 'Laadi PDF', en: 'Download PDF' },
  'contract.sample_title': { et: 'Pole lepingut k\u00e4ep\u00e4rast?', en: 'No contract at hand?' },
  'contract.sample_desc': { et: 'Laadi n\u00e4idis IKT-leping testimiseks', en: 'Load a sample ICT contract for testing' },
  'contract.load_sample': { et: 'Laadi n\u00e4idisleping', en: 'Load sample contract' },
  'contract.download_sample': { et: 'Vaata PDF', en: 'View PDF' },
  'contract.risk_areas': { et: 'K\u00f5ige riskantsemad kohad', en: 'Highest Risk Areas' },
  'contract.risk_areas_desc': { et: 'Need n\u00f5uded vajavad kohest t\u00e4helepanu', en: 'These requirements need immediate attention' },
  'contract.demo_title': { et: 'Proovi n\u00e4idislepinguga', en: 'Try with sample contract' },
  'contract.demo_desc': { et: 'Genereeri n\u00e4idis IKT-leping ja vaata, kuidas DORA Art. 30 kontroll t\u00f6\u00f6tab. See on t\u00e4iesti tasuta.', en: 'Generate a sample ICT contract and see how DORA Art. 30 check works. This is completely free.' },
  'contract.generate_sample': { et: 'Genereeri n\u00e4idisleping', en: 'Generate sample contract' },
  'contract.suggested_clauses': { et: 'Soovituslikud lepinguklauslid', en: 'Suggested contract clauses' },
  'contract.suggested_clauses_desc': { et: 'Lisage need klauslid oma lepingusse puuduste k\u00f5rvaldamiseks', en: 'Add these clauses to your contract to fix gaps' },
  'contract.reg_references': { et: 'Regulatiivsed viited', en: 'Regulatory References' },
  'contract.guidelines': { et: 'juhised', en: 'Guidelines' },
  'contract.share_title': { et: 'Saada tulemused e-mailile', en: 'Send results to email' },
  'contract.share_desc': { et: 'Saame saata teile kokkuv\u00f5tte ja uuendused', en: 'We can send you a summary and updates' },
  'contract.email_placeholder': { et: 'teie@ettevote.ee', en: 'your@company.com' },
  'contract.send': { et: 'Saada', en: 'Send' },
  'contract.email_saved': { et: 'E-mail salvestatud! Saadame teile tulemused.', en: 'Email saved! We will send you the results.' },
  'contract.loading_results': { et: 'Tulemuste laadimine...', en: 'Loading results...' },
  'contract.error_loading': { et: 'Tulemuste laadimine ebaõnnestus', en: 'Failed to load results' },
  'contract.defensibility': { et: 'kaitstav', en: 'defensible' },
  'contract.evidence_mapping': { et: 'Tõendite kaardistamine', en: 'Evidence Mapping' },
  'contract.evidence_desc': { et: 'Kuidas teie leping vastab igale DORA Art. 30 nõudele', en: 'How your contract addresses each DORA Art. 30 requirement' },
  'contract.filter_all': { et: 'Kõik', en: 'All' },
  'contract.covered': { et: 'Kaetud', en: 'Covered' },
  'contract.weak': { et: 'Nõrk', en: 'Weak' },
  'contract.th_article': { et: 'Artikkel', en: 'Article' },
  'contract.th_requirement': { et: 'Nõue', en: 'Requirement' },
  'contract.th_status': { et: 'Staatus', en: 'Status' },
  'contract.th_evidence': { et: 'Tõend', en: 'Evidence' },
  'contract.tab_gaps': { et: 'Lüngad ja soovitused', en: 'Gaps and Recommendations' },
  'contract.back': { et: 'Tagasi', en: 'Back' },

  // Contract Comparison
  'comparison.loading': { et: 'Võrdluse laadimine...', en: 'Loading comparison...' },
  'comparison.title': { et: 'Lepingu vs mudeli võrdlus', en: 'Contract vs Model Comparison' },
  'comparison.subtitle': { et: 'Teie lepingu klauslid vs DORA Art. 30 mudelklauslid', en: 'Your contract clauses vs DORA Art. 30 model clauses' },
  'comparison.compare_button': { et: 'Võrdle mudeliga', en: 'Compare with Model' },
  'comparison.status_found': { et: 'Leitud', en: 'Found' },
  'comparison.status_partial': { et: 'Osaline', en: 'Partial' },
  'comparison.status_missing': { et: 'Puudu', en: 'Missing' },
  'comparison.filter_all': { et: 'Kõik', en: 'All' },
  'comparison.filter_gaps': { et: 'Ainult lüngad', en: 'Only Gaps' },
  'comparison.th_requirement': { et: 'Nõue', en: 'Requirement' },
  'comparison.th_your_contract': { et: 'Teie leping', en: 'Your Contract' },
  'comparison.th_model_clause': { et: 'Mudelklausel', en: 'Model Clause' },
  'comparison.th_status': { et: 'Staatus', en: 'Status' },
  'comparison.not_found': { et: 'Klauslit ei leitud', en: 'Clause not found' },
  'comparison.your_text': { et: 'Teie lepingu tekst', en: 'Your Contract Text' },
  'comparison.model_text': { et: 'Mudelklausel', en: 'Model Clause' },
  'comparison.clause_not_present': { et: 'Seda klauslit teie lepingus ei leitud. Soovitame lisada vastava sätte.', en: 'This clause was not found in your contract. We recommend adding the corresponding provision.' },
  'comparison.model_source': { et: 'Allikas', en: 'Source' },
  'comparison.export_pdf': { et: 'Ekspordi PDF', en: 'Export PDF' },
  'comparison.back_to_results': { et: 'Tagasi tulemuste juurde', en: 'Back to Results' },
  'comparison.legend_found': { et: 'Täielikult kaetud', en: 'Fully covered' },
  'comparison.legend_partial': { et: 'Osaliselt kaetud', en: 'Partially covered' },
  'comparison.legend_missing': { et: 'Puudub lepingust', en: 'Missing from contract' },

  // Contract Generator
  'generator.badge': { et: 'Lepingu generaator', en: 'Contract Generator' },
  'generator.title': { et: 'Genereeri DORA-vastav leping', en: 'Generate DORA-Compliant Contract' },
  'generator.subtitle': { et: 'Vali klauslid ja lae alla professionaalne IKT teenuse leping, mis vastab DORA Art. 30 nõuetele.', en: 'Select clauses and download a professional ICT service contract that meets DORA Art. 30 requirements.' },
  'generator.select_clauses': { et: 'Vali klauslid', en: 'Select Clauses' },
  'generator.select_all': { et: 'Vali kõik', en: 'Select all' },
  'generator.select_none': { et: 'Tühista', en: 'Clear' },
  'generator.selected': { et: 'Valitud', en: 'Selected' },
  'generator.clauses': { et: 'klauslit', en: 'clauses' },
  'generator.full_compliance': { et: 'Täielik DORA Art. 30 vastavus', en: 'Full DORA Art. 30 compliance' },
  'generator.partial_compliance': { et: 'Vali kõik 8 klauslit täieliku vastavuse jaoks', en: 'Select all 8 clauses for full compliance' },
  'generator.preview': { et: 'Lepingu eelvaade', en: 'Contract Preview' },
  'generator.download_pdf': { et: 'Lae PDF', en: 'Download PDF' },
  'generator.empty_preview': { et: 'Vali vähemalt üks klausel, et näha lepingu eelvaadet', en: 'Select at least one clause to see the contract preview' },
  'generator.analyze_contract': { et: 'Analüüsi seda lepingut', en: 'Analyze This Contract' },
  'generator.analyzing': { et: 'Analüüsimine...', en: 'Analyzing...' },
  'nav.generator': { et: 'Genereeri leping', en: 'Generate Contract' },

  // Nav - Code Analysis
  'nav.code': { et: 'Koodi audit', en: 'Code Audit' },

  // Code Analysis
  'code.badge': { et: 'ULTRA MODE \u2022 Halastamatu koodiaudit', en: 'ULTRA MODE \u2022 Ruthless Code Audit' },
  'code.title': { et: 'Koodi audit', en: 'Code Audit' },
  'code.subtitle': { et: 'AI-genereeritud koodi tuvastamine, turvaaaukude leidmine ja finantsilise m\u00f5ju hindamine. Knight Capital kaotas 45 minutiga $460M \u2014 sinu kood v\u00f5ib olla j\u00e4rgmine.', en: 'AI-generated code detection, vulnerability scanning and financial impact assessment. Knight Capital lost $460M in 45 minutes \u2014 your code could be next.' },
  'code.company': { et: 'Ettev\u00f5tte nimi', en: 'Company Name' },
  'code.revenue': { et: 'Aastane k\u00e4ive (\u20ac)', en: 'Annual Revenue (\u20ac)' },
  'code.revenue_hint': { et: 'Kahjude arvutamiseks \u2014 t\u00e4psem k\u00e4ive = t\u00e4psem anal\u00fc\u00fcs', en: 'For loss calculations \u2014 more accurate revenue = more accurate analysis' },
  'code.drop_files': { et: 'Lohista koodifailid siia v\u00f5i kliki valimiseks', en: 'Drag code files here or click to select' },
  'code.files_selected': { et: 'faili valitud', en: 'files selected' },
  'code.start_analysis': { et: 'K\u00e4ivita audit', en: 'Start Audit' },
  'code.analyzing_iteration': { et: 'Anal\u00fc\u00fcsin \u2014 iteratsioon', en: 'Analyzing \u2014 iteration' },
  'code.iteration': { et: 'Iteratsioon', en: 'Iteration' },
  'code.next_iteration': { et: 'J\u00e4rgmine iteratsioon', en: 'Next iteration' },
  'code.ai_percentage': { et: 'AI-genereeritud kood', en: 'AI-Generated Code' },
  'code.ai_warning': { et: 'AI-genereeritud kood suurendab teadmatust ja hoolduskulusid eksponentsiaalselt', en: 'AI-generated code increases uncertainty and maintenance costs exponentially' },
  'code.verdict': { et: '\u00dcldine hinnang', en: 'Overall Verdict' },
  'code.total_exposure': { et: 'Kogu finantsrisk', en: 'Total Financial Exposure' },
  'code.ai_indicators': { et: 'AI-genereerimise tunnused', en: 'AI Generation Indicators' },
  'code.security_vulns': { et: 'Turvaaaugud', en: 'Security Vulnerabilities' },
  'code.exploit': { et: '\u00c4rakasutamine', en: 'Exploit' },
  'code.real_world': { et: 'Reaalne paralleel', en: 'Real-World Parallel' },
  'code.fix': { et: 'Parandus', en: 'Fix' },
  'code.fix_critique': { et: 'Miks see parandus tavaliselt eba\u00f5nnestub', en: 'Why this fix usually fails' },
  'code.quality_issues': { et: 'Koodikvaliteedi probleemid', en: 'Code Quality Issues' },
  'code.financial_deep': { et: 'Finantsriski s\u00fcvanal\u00fc\u00fcs', en: 'Financial Risk Deep Dive' },
  'code.annual_loss': { et: 'Hinnanguline aastane kahju', en: 'Estimated Annual Loss' },
  'code.catastrophe_12m': { et: 'Katastroofi t\u00f5en\u00e4osus 12 kuud', en: 'Catastrophe Probability 12mo' },
  'code.compliance_risk': { et: 'Vastavuse risk', en: 'Compliance Risk' },
  'code.new_analysis': { et: 'Uus audit', en: 'New Audit' },
  'code.mock_title': { et: 'Proovi n\u00E4idis-koodibaasiga', en: 'Try with mock codebase' },
  'code.mock_badge': { et: 'Kiire demo', en: 'Quick demo' },
  'code.mock_desc': { et: 'Vali n\u00E4idis-koodibaas ja kvaliteeditase. N\u00E4ed kohe, mida halva koodi hooldamine ettev\u00F5ttele maksma l\u00E4heb.', en: 'Pick a mock codebase and quality level. See immediately what maintaining bad code costs your company.' },
  'code.quality_level': { et: 'Hindamise vaatenurk', en: 'Assessment lens' },
  'code.quality_lens_hint': { et: 'M\u00F5jutab anal\u00FC\u00FCsi fookust ja kahju arvutusi', en: 'Affects analysis focus and damage calculations' },
  'code.load_mock': { et: 'Laadi n\u00E4idis-koodibaas', en: 'Load mock codebase' },
  'code.hourly_rate': { et: 'Arendaja tunnihind (\u20AC)', en: 'Developer hourly rate (\u20AC)' },
  'code.hourly_hint': { et: 'Eesti keskmine: \u20AC65\u201395/h. PM-id armastavad seda numbrit.', en: 'Estonian average: \u20AC65\u201395/h. PMs love this number.' },
  'code.team_size': { et: 'Meeskonna suurus (arendajaid)', en: 'Team size (developers)' },
  'code.dev_months': { et: 'Projekti kestus (kuud)', en: 'Project duration (months)' },
  'code.pm_dashboard': { et: 'PM M\u00F5juanal\u00FC\u00FCs', en: 'PM Impact Dashboard' },
  'code.pm_wasted_hours': { et: 'Raisatud tunnid', en: 'Wasted Hours' },
  'code.pm_wasted_eur': { et: 'Raisatud eurod', en: 'Wasted EUR' },
  'code.pm_fix_hours': { et: 'Parandamise tunnid', en: 'Fix Hours' },
  'code.pm_fix_cost': { et: 'Paranduskulu', en: 'Fix Cost' },
  'code.pm_team_impact': { et: 'Meeskonna m\u00F5ju', en: 'Team Impact' },
  'code.pm_brutal': { et: 'Karm t\u00F5de', en: 'The Brutal Truth' },

  // Nav - Simulator
  'nav.simulator': { et: 'Simulaator', en: 'Simulator' },

  // Incident Simulator
  'sim.badge': { et: 'Unikaalne t\u00f6\u00f6riist \u2022 Intsidendisimulaator', en: 'Unique Tool \u2022 Incident Simulator' },
  'sim.title': { et: 'IKT intsidendi simulaator', en: 'ICT Incident Simulator' },
  'sim.subtitle': { et: 'Simuleerige reaalseid k\u00fcberintsidente ja vaadake, kuidas teie DORA vastavus p\u00fc\u00fcab. N\u00e4ete t\u00e4pselt, millised l\u00fcngad muutuvad haavatavusteks.', en: 'Simulate real-world cyber incidents and see how your DORA compliance holds up. See exactly which gaps become vulnerabilities.' },
  'sim.no_data_title': { et: 'Hindamisandmed puuduvad', en: 'No Assessment Data' },
  'sim.no_data_desc': { et: 'Simulaatori kasutamiseks tehke k\u00f5igepealt DORA vastavuse hindamine.', en: 'Complete a DORA compliance assessment first to use the simulator.' },
  'sim.start_assessment': { et: 'Alusta hindamist', en: 'Start Assessment' },
  'sim.choose_scenario': { et: 'Valige intsidendi stsenaarium', en: 'Choose an Incident Scenario' },
  'sim.choose_desc': { et: 'Iga stsenaarium p\u00f5hineb reaalsetel juhtumitel ja kaardistab m\u00f5ju teie DORA vastavusprofiilile.', en: 'Each scenario is based on real incidents and maps impact to your DORA compliance profile.' },
  'sim.areas_affected': { et: 'valdkonda m\u00f5jutatud', en: 'areas affected' },
  'sim.using_assessment': { et: 'Kasutatav hindamine', en: 'Using assessment' },
  'sim.back': { et: 'Tagasi stsenaariumite juurde', en: 'Back to scenarios' },
  'sim.exposure': { et: 'Haavatavus', en: 'Exposure' },
  'sim.gaps_exploited': { et: '\u00c4rakasutatud l\u00fcngad', en: 'Gaps Exploited' },
  'sim.protected': { et: 'Kaitstud', en: 'Protected' },
  'sim.response_time': { et: 'Taastumisaeg', en: 'Recovery Time' },
  'sim.days': { et: 'p', en: 'd' },
  'sim.day': { et: 'P\u00e4ev', en: 'Day' },
  'sim.regulatory_outcome': { et: 'Regulatiivne tagaj\u00e4rg', en: 'Regulatory Outcome' },
  'sim.outcome_FINE': { et: 'Trahv', en: 'Fine' },
  'sim.outcome_FINE_desc': { et: 'Finantsinspektsioon m\u00e4\u00e4rab t\u00f5en\u00e4oliselt trahvi. Teie DORA vastavusel on olulisi l\u00fcnki, mis v\u00f5imaldasid intsidendi toimumist.', en: 'Finantsinspektsioon will likely impose a fine. Your DORA compliance has significant gaps that enabled the incident.' },
  'sim.outcome_PRESCRIPTION': { et: 'Ettekirjutus', en: 'Prescription' },
  'sim.outcome_PRESCRIPTION_desc': { et: 'Finantsinspektsioon esitab ettekirjutuse koos t\u00e4htajaga puuduste k\u00f5rvaldamiseks. Trahvi v\u00f5idakse m\u00e4\u00e4rata, kui n\u00f5udeid ei t\u00e4ideta.', en: 'Finantsinspektsioon will issue a prescription with a deadline to fix deficiencies. Fines may follow if requirements are not met.' },
  'sim.outcome_WARNING': { et: 'Hoiatus', en: 'Warning' },
  'sim.outcome_WARNING_desc': { et: 'T\u00f5en\u00e4oliselt saate hoiatuse ja soovitused. Vastavus on enamasti tagatud, kuid m\u00f5ned kohad vajavad t\u00e4iustamist.', en: 'You will likely receive a warning and recommendations. Compliance is mostly ensured but some areas need improvement.' },
  'sim.outcome_COMPLIANT': { et: 'Vastav', en: 'Compliant' },
  'sim.outcome_COMPLIANT_desc': { et: 'Teie DORA vastavus on tugev. Intsident k\u00e4sitletakse korrektselt ning regulatiivset sekkumist ei ole oodata.', en: 'Your DORA compliance is strong. The incident would be handled correctly and no regulatory intervention is expected.' },
  'sim.max_fine': { et: 'Maksimaalne trahv', en: 'Maximum fine' },
  'sim.of_turnover': { et: 'aastasest k\u00e4ibest', en: 'of annual turnover' },
  'sim.timeline': { et: 'Intsidendi ajajoon', en: 'Incident Timeline' },
  'sim.exploited_gaps': { et: '\u00e4rakasutatud l\u00fcnka', en: 'exploited gaps' },
  'sim.protected_areas': { et: 'kaitstud valdkonda', en: 'protected areas' },
  'sim.real_world': { et: 'Reaalne n\u00e4ide', en: 'Real-World Example' },
  'sim.loss': { et: 'Kahju', en: 'Loss' },
  'sim.try_another': { et: 'Proovi teist stsenaariumit', en: 'Try Another Scenario' },
  'sim.improve_score': { et: 'Paranda vastavust', en: 'Improve Compliance' },

  // Scenarios
  'sim.scenario_ransomware': { et: 'Lunavararunnak', en: 'Ransomware Attack' },
  'sim.scenario_ransomware_desc': { et: 'K\u00fcberrundajad kr\u00fcpteerivad teie IKT-s\u00fcsteemid ja n\u00f5uavad lunaraha. Teenused on maas.', en: 'Attackers encrypt your ICT systems and demand ransom. Services are down.' },
  'sim.scenario_cloud_outage': { et: 'Pilveteenuse katkestus', en: 'Cloud Service Outage' },
  'sim.scenario_cloud_outage_desc': { et: 'Teie p\u00f5hiline pilveteenuse pakkuja kogeb pikaajalist katkestust.', en: 'Your primary cloud provider experiences an extended outage.' },
  'sim.scenario_data_breach': { et: 'Andmeleke', en: 'Data Breach' },
  'sim.scenario_data_breach_desc': { et: 'Klientide isikuandmed ja finantsandmed lekivad avalikuks.', en: 'Customer personal and financial data is exposed publicly.' },
  'sim.scenario_supply_chain': { et: 'Tarneahela r\u00fcnnak', en: 'Supply Chain Attack' },
  'sim.scenario_supply_chain_desc': { et: 'Teie IKT-teenusepakkuja tarkvara on kompromiteeritud tagauksega.', en: 'Your ICT provider\'s software is compromised with a backdoor.' },
  'sim.scenario_insider_threat': { et: 'Sisemine oht', en: 'Insider Threat' },
  'sim.scenario_insider_threat_desc': { et: 'Endine t\u00f6\u00f6taja pääseb ligi konfidentsiaalsetele andmetele ja s\u00fcsteemidele.', en: 'Former employee accesses confidential data and systems.' },
  'sim.scenario_api_attack': { et: 'API r\u00fcnnak', en: 'API Attack' },
  'sim.scenario_api_attack_desc': { et: 'R\u00fcndajad kasutavad \u00e4ra teie avaliku API haavatavusi massiliseks andmete kogumiseks.', en: 'Attackers exploit your public API vulnerabilities for mass data extraction.' },

  // Timeline events - Ransomware
  'sim.tl_ransomware_detection': { et: 'Intsidendi tuvastamine', en: 'Incident Detection' },
  'sim.tl_ransomware_detection_desc': { et: 'S\u00fcsteemid muutuvad k\u00e4ttesaamatuks. IT-meeskond tuvastab lunavara.', en: 'Systems become inaccessible. IT team identifies ransomware.' },
  'sim.tl_ransomware_containment': { et: 'Isoleerimine', en: 'Containment' },
  'sim.tl_ransomware_containment_desc': { et: 'Nakatunud s\u00fcsteemid isoleeritakse. Hinnang leviku ulatusele.', en: 'Infected systems isolated. Assessment of spread extent.' },
  'sim.tl_ransomware_notification': { et: 'Teavitamine', en: 'Notification' },
  'sim.tl_ransomware_notification_desc': { et: 'Finantsinspektsioon ja kliendid teavitatakse intsidendist (DORA Art. 19).', en: 'Finantsinspektsioon and clients notified of incident (DORA Art. 19).' },
  'sim.tl_ransomware_investigation': { et: 'Uurimine', en: 'Investigation' },
  'sim.tl_ransomware_investigation_desc': { et: 'Forenseeriline anal\u00fc\u00fcs. Sissep\u00e4\u00e4su vektori tuvastamine.', en: 'Forensic analysis. Entry vector identification.' },
  'sim.tl_ransomware_recovery': { et: 'Taastamine', en: 'Recovery' },
  'sim.tl_ransomware_recovery_desc': { et: 'S\u00fcsteemide taastamine varukoopiatest. Teenuste j\u00e4rk-j\u00e4rguline taastamine.', en: 'System restoration from backups. Gradual service recovery.' },
  'sim.tl_ransomware_regulatory': { et: 'Regulatiivne j\u00e4relkontroll', en: 'Regulatory Follow-up' },
  'sim.tl_ransomware_regulatory_desc': { et: 'Finantsinspektsiooni audit DORA vastavuse kohta. Otsus sanktsioonide osas.', en: 'Finantsinspektsioon audit on DORA compliance. Decision on sanctions.' },

  // Timeline events - Cloud outage
  'sim.tl_cloud_outage_detection': { et: 'Katkestuse tuvastamine', en: 'Outage Detection' },
  'sim.tl_cloud_outage_detection_desc': { et: 'Monitooring tuvastab pilveteenuse katkestuse. Kliendid teatavad probleemidest.', en: 'Monitoring detects cloud service outage. Clients report issues.' },
  'sim.tl_cloud_outage_containment': { et: 'Eskaleermine', en: 'Escalation' },
  'sim.tl_cloud_outage_containment_desc': { et: '\u00dchendusse astumine teenusepakkujaga. BCP aktiveerimine.', en: 'Contact with provider. BCP activation.' },
  'sim.tl_cloud_outage_notification': { et: 'Klientide teavitamine', en: 'Client Notification' },
  'sim.tl_cloud_outage_notification_desc': { et: 'Klientide ja regulaatori teavitamine teenuse katkestusest.', en: 'Notification of clients and regulator about service disruption.' },
  'sim.tl_cloud_outage_investigation': { et: 'M\u00f5juanal\u00fc\u00fcs', en: 'Impact Analysis' },
  'sim.tl_cloud_outage_investigation_desc': { et: 'Kahjude ja m\u00f5jutatud teenuste kaardistamine.', en: 'Mapping of damages and affected services.' },
  'sim.tl_cloud_outage_recovery': { et: 'Teenuse taastamine', en: 'Service Recovery' },
  'sim.tl_cloud_outage_recovery_desc': { et: 'Teenuse taastamine p\u00e4rast pakkuja parandust v\u00f5i alternatiivile \u00fcleminek.', en: 'Service recovery after provider fix or migration to alternative.' },
  'sim.tl_cloud_outage_regulatory': { et: 'Aruandlus', en: 'Reporting' },
  'sim.tl_cloud_outage_regulatory_desc': { et: 'L\u00f5pparuanne regulaatorile. V\u00e4ljumisstrateegiate \u00fclevaatamine.', en: 'Final report to regulator. Review of exit strategies.' },

  // Timeline events - Data breach
  'sim.tl_data_breach_detection': { et: 'Lekke avastamine', en: 'Breach Discovery' },
  'sim.tl_data_breach_detection_desc': { et: 'Andmeleke avastatakse (v\u00f5i kolmas osapool teavitab).', en: 'Data breach discovered (or third party reports it).' },
  'sim.tl_data_breach_containment': { et: 'Lekke piiramine', en: 'Breach Containment' },
  'sim.tl_data_breach_containment_desc': { et: 'Juurdep\u00e4\u00e4su sulgemine. Lekkinud andmete ulatuse hindamine.', en: 'Access revoked. Assessment of exposed data scope.' },
  'sim.tl_data_breach_notification': { et: 'GDPR + DORA teavitus', en: 'GDPR + DORA Notification' },
  'sim.tl_data_breach_notification_desc': { et: '72h GDPR teavitus + DORA Art. 19 kohaselt regulaatori teavitamine.', en: '72h GDPR notification + DORA Art. 19 regulator notification.' },
  'sim.tl_data_breach_investigation': { et: 'Forenseeriline uurimine', en: 'Forensic Investigation' },
  'sim.tl_data_breach_investigation_desc': { et: 'Lekke p\u00f5hjuse v\u00e4ljaselgitamine. Ohustatud kirjete arvu m\u00e4\u00e4ramine.', en: 'Root cause analysis. Determination of affected record count.' },
  'sim.tl_data_breach_recovery': { et: 'Klientide teavitamine', en: 'Client Communication' },
  'sim.tl_data_breach_recovery_desc': { et: 'Individuaalsed teavitused m\u00f5jutatud klientidele. Kreediitmonitooringute pakkumine.', en: 'Individual notifications to affected clients. Credit monitoring offers.' },
  'sim.tl_data_breach_regulatory': { et: 'Mitmekordne audit', en: 'Multiple Audits' },
  'sim.tl_data_breach_regulatory_desc': { et: 'Finantsinspektsiooni DORA audit + Andmekaitse Inspektsiooni GDPR audit.', en: 'Finantsinspektsioon DORA audit + Data Protection Authority GDPR audit.' },

  // Timeline events - Supply chain
  'sim.tl_supply_chain_detection': { et: 'Kompromissi avastamine', en: 'Compromise Discovery' },
  'sim.tl_supply_chain_detection_desc': { et: 'Kahtlane tegevus tuvastatud kolmanda osapoole tarkvara kaudu.', en: 'Suspicious activity detected through third-party software.' },
  'sim.tl_supply_chain_containment': { et: 'Isolatsiooni faas', en: 'Isolation Phase' },
  'sim.tl_supply_chain_containment_desc': { et: 'Kompromiteeritud tarkvara keelamine. Ohuhinnang.', en: 'Compromised software blocked. Threat assessment.' },
  'sim.tl_supply_chain_notification': { et: 'Sektori teavitamine', en: 'Sector Notification' },
  'sim.tl_supply_chain_notification_desc': { et: 'DORA Art. 19 aruandlus. Sektori\u00fclene hoiatuse edastamine.', en: 'DORA Art. 19 reporting. Cross-sector warning dissemination.' },
  'sim.tl_supply_chain_investigation': { et: 'Tarneahela audit', en: 'Supply Chain Audit' },
  'sim.tl_supply_chain_investigation_desc': { et: 'K\u00f5ikide kolmandate osapoolte allhankijate kontrollimine.', en: 'Review of all third-party subcontractors.' },
  'sim.tl_supply_chain_recovery': { et: 'Alternatiivide rakendamine', en: 'Alternative Implementation' },
  'sim.tl_supply_chain_recovery_desc': { et: 'Asendus- v\u00f5i parandatud tarkvara paigaldamine.', en: 'Replacement or patched software deployment.' },
  'sim.tl_supply_chain_regulatory': { et: 'V\u00e4ljumisstrateegia hindamine', en: 'Exit Strategy Review' },
  'sim.tl_supply_chain_regulatory_desc': { et: 'Regulaator hindab teie teenusepakkujate haldust ja v\u00e4ljumisplaane.', en: 'Regulator evaluates your vendor management and exit plans.' },

  // Timeline events - Insider threat
  'sim.tl_insider_threat_detection': { et: 'Kahtlase tegevuse tuvastamine', en: 'Suspicious Activity Detection' },
  'sim.tl_insider_threat_detection_desc': { et: 'Endise t\u00f6\u00f6taja volitamata juurdep\u00e4\u00e4s tuvastatud logidest.', en: 'Former employee unauthorized access detected from logs.' },
  'sim.tl_insider_threat_containment': { et: 'Juurdep\u00e4\u00e4su t\u00fchimine', en: 'Access Revocation' },
  'sim.tl_insider_threat_containment_desc': { et: 'K\u00f5ik seotud kontod suletakse. Parem\u00f5iguste audit.', en: 'All related accounts closed. Privilege audit.' },
  'sim.tl_insider_threat_notification': { et: 'Sisemine teavitamine', en: 'Internal Notification' },
  'sim.tl_insider_threat_notification_desc': { et: 'Juhtkond, \u00f5igusosakond ja vajadusel regulaator teavitatakse.', en: 'Management, legal, and if necessary regulator notified.' },
  'sim.tl_insider_threat_investigation': { et: 'Siseuurimine', en: 'Internal Investigation' },
  'sim.tl_insider_threat_investigation_desc': { et: 'Andmetele juurdep\u00e4\u00e4su logide anal\u00fc\u00fcs. Lekkinud andmete hindamine.', en: 'Data access log analysis. Assessment of exposed data.' },
  'sim.tl_insider_threat_recovery': { et: 'Turvameetmete t\u00e4iustamine', en: 'Security Enhancement' },
  'sim.tl_insider_threat_recovery_desc': { et: 'Juurdep\u00e4\u00e4su halduse \u00fclevaatamine. MFA rakendamine.', en: 'Access management review. MFA implementation.' },
  'sim.tl_insider_threat_regulatory': { et: 'Vastavuse kontroll', en: 'Compliance Review' },
  'sim.tl_insider_threat_regulatory_desc': { et: 'Siseauditi aruanne ja regulaatorile esitamine vajadusel.', en: 'Internal audit report and submission to regulator if needed.' },

  // Timeline events - API attack
  'sim.tl_api_attack_detection': { et: 'R\u00fcnnaku tuvastamine', en: 'Attack Detection' },
  'sim.tl_api_attack_detection_desc': { et: 'Anomaalne API liiklus tuvastatud. Massiline andmep\u00e4ring.', en: 'Anomalous API traffic detected. Mass data query.' },
  'sim.tl_api_attack_containment': { et: 'API piiramine', en: 'API Throttling' },
  'sim.tl_api_attack_containment_desc': { et: 'Haavatava endpointi sulgemine. Rate limiting rakendamine.', en: 'Vulnerable endpoint closed. Rate limiting applied.' },
  'sim.tl_api_attack_notification': { et: 'Intsidendi teavitus', en: 'Incident Notification' },
  'sim.tl_api_attack_notification_desc': { et: 'Regulaatori ja m\u00f5jutatud klientide teavitamine.', en: 'Regulator and affected clients notified.' },
  'sim.tl_api_attack_investigation': { et: 'Haavatavuse anal\u00fc\u00fcs', en: 'Vulnerability Analysis' },
  'sim.tl_api_attack_investigation_desc': { et: 'API turvaaugu p\u00f5hjuse ja andmelekke ulatuse anal\u00fc\u00fcs.', en: 'API vulnerability root cause and data exposure scope analysis.' },
  'sim.tl_api_attack_recovery': { et: 'Turvap\u00e4\u00e4su parandamine', en: 'Security Patching' },
  'sim.tl_api_attack_recovery_desc': { et: 'API haavatavuse parandamine. Turvatestimine enne taask\u00e4ivitamist.', en: 'API vulnerability fix. Security testing before relaunch.' },
  'sim.tl_api_attack_regulatory': { et: 'L\u00f5pparuanne', en: 'Final Report' },
  'sim.tl_api_attack_regulatory_desc': { et: 'Kogu intsident dokumenteeritud. Regulaatorile l\u00f5pparuande esitamine.', en: 'Full incident documented. Final report submitted to regulator.' },

  // Pillar Info
  'pillar.back': { et: 'Tagasi avalehele', en: 'Back to home' },
  'pillar.overview': { et: 'Ülevaade', en: 'Overview' },
  'pillar.key_requirements': { et: 'Peamised nõuded', en: 'Key Requirements' },
  'pillar.resources': { et: 'Regulatiivsed viited', en: 'Regulatory Resources' },
  'pillar.cta_title': { et: 'Kontrolli oma lepingut', en: 'Check your contract' },
  'pillar.cta_desc': { et: 'Vaata, kuidas sinu IKT-leping vastab DORA Art. 30 nõuetele.', en: 'See how your ICT contract complies with DORA Art. 30 requirements.' },
  'pillar.not_found': { et: 'Sammast ei leitud', en: 'Pillar not found' },
  'pillar.context_title': { et: 'Kuidas see sammas seostub lepingu kontrolliga?', en: 'How does this pillar relate to contract checking?' },
  'pillar.context_third_party': { et: 'See on meie tööriista põhifookus. Art. 30 sätestab kohustuslikud lepingutingimused, mida meie tööriist kontrollib.', en: 'This is the main focus of our tool. Art. 30 establishes mandatory contract provisions that our tool checks.' },
  'pillar.context_other': { et: 'See sammas on seotud DORA üldise raamistikuga. Meie tööriist keskendub Art. 30 lepingutingimustele (kolmandate osapoolte sammas).', en: 'This pillar is part of the broader DORA framework. Our tool focuses on Art. 30 contract provisions (third-party pillar).' },

  // Landing - Auth indicators
  'landing.requires_login': { et: 'Nõuab sisselogimist', en: 'Requires login' },

  // Auth
  'auth.login': { et: 'Logi sisse', en: 'Log In' },
  'auth.register': { et: 'Registreeru', en: 'Register' },
  'auth.logout': { et: 'Logi v\u00e4lja', en: 'Log Out' },
  'auth.login_btn': { et: 'Sisene', en: 'Sign In' },
  'auth.register_btn': { et: 'Registreeru', en: 'Sign Up' },
  'auth.email': { et: 'E-post', en: 'Email' },
  'auth.password': { et: 'Parool', en: 'Password' },
  'auth.confirm_password': { et: 'Kinnita parool', en: 'Confirm Password' },
  'auth.full_name': { et: 'T\u00e4isnimi', en: 'Full Name' },
  'auth.no_account': { et: 'Pole kontot?', en: "Don't have an account?" },
  'auth.have_account': { et: 'On juba konto?', en: 'Already have an account?' },
  'auth.register_link': { et: 'Registreeru siin', en: 'Register here' },
  'auth.login_link': { et: 'Logi sisse siin', en: 'Log in here' },
  'auth.error_invalid': { et: 'Vale e-post v\u00f5i parool', en: 'Invalid email or password' },
  'auth.error_exists': { et: 'See e-post on juba registreeritud', en: 'This email is already registered' },
  'auth.error_mismatch': { et: 'Paroolid ei kattu', en: 'Passwords do not match' },
  'auth.error_name_required': { et: 'Nimi on kohustuslik', en: 'Name is required' },
  'auth.error_email_required': { et: 'E-post on kohustuslik', en: 'Email is required' },
  'auth.error_email_invalid': { et: 'Sisestage kehtiv e-posti aadress', en: 'Please enter a valid email address' },
  'auth.error_password_required': { et: 'Parool on kohustuslik', en: 'Password is required' },
  'auth.error_password_short': { et: 'Parool peab olema v\u00e4hemalt 6 t\u00e4hem\u00e4rki', en: 'Password must be at least 6 characters' },
  'auth.error_generic': { et: 'Midagi l\u00e4ks valesti. Palun proovige uuesti.', en: 'Something went wrong. Please try again.' },

  // Footer
  'footer.built_for': { et: 'Loodud Eesti finantssektori ettev\u00f5tetele', en: 'Built for Estonian financial sector companies' },
  'footer.regulation': { et: 'Digitaalse tegevuskerksuse m\u00e4\u00e4rus', en: 'Digital Operational Resilience Act' },
  'footer.dora_text': { et: 'DORA tekst', en: 'DORA text' },
  'footer.privacy': { et: 'Privaatsus', en: 'Privacy' },

  // Privacy page
  'privacy.title': { et: 'Privaatsuspoliitika', en: 'Privacy Policy' },
  'privacy.subtitle': { et: 'Kuidas me teie andmeid kaitseme', en: 'How we protect your data' },
  'privacy.data_collection_title': { et: 'Milliseid andmeid kogume', en: 'What data we collect' },
  'privacy.data_collection_desc': { et: 'Kogume ainult teenuse osutamiseks vajalikke andmeid:', en: 'We only collect data necessary to provide the service:' },
  'privacy.data_1': { et: 'E-posti aadress (registreerimisel)', en: 'Email address (upon registration)' },
  'privacy.data_2': { et: 'Üleslaaditud lepingute sisu (analüüsi ajaks)', en: 'Uploaded contract content (during analysis)' },
  'privacy.data_3': { et: 'Hindamiste tulemused', en: 'Assessment results' },
  'privacy.storage_title': { et: 'Andmete säilitamine', en: 'Data storage' },
  'privacy.storage_desc': { et: 'Üleslaaditud lepinguid ei salvestata püsivalt. Lepingu sisu töödeldakse ainult analüüsi ajal ja kustutatakse pärast tulemuste genereerimist. Teie e-posti aadressi ja hindamistulemusi säilitatakse turvaliselt EL-i serverites.', en: 'Uploaded contracts are not permanently stored. Contract content is processed only during analysis and deleted after results are generated. Your email address and assessment results are stored securely on EU servers.' },
  'privacy.rights_title': { et: 'Teie õigused', en: 'Your rights' },
  'privacy.rights_desc': { et: 'GDPR alusel on teil õigus:', en: 'Under GDPR, you have the right to:' },
  'privacy.right_1': { et: 'Küsida ligipääsu oma andmetele', en: 'Request access to your data' },
  'privacy.right_2': { et: 'Nõuda andmete parandamist või kustutamist', en: 'Request correction or deletion of your data' },
  'privacy.right_3': { et: 'Esitada vastuväiteid andmete töötlemisele', en: 'Object to data processing' },
  'privacy.gdpr_title': { et: 'GDPR vastavus', en: 'GDPR compliance' },
  'privacy.gdpr_desc': { et: 'See teenus on loodud GDPR nõuetele vastavalt. Me ei jaga teie andmeid kolmandate osapooltega ilma teie nõusolekuta, välja arvatud seadusega nõutud juhtudel.', en: 'This service is built in compliance with GDPR requirements. We do not share your data with third parties without your consent, except when required by law.' },
  'privacy.updated': { et: 'Viimati uuendatud', en: 'Last updated' },

  // Negotiations
  'nav.negotiations': { et: 'L\u00e4bir\u00e4\u00e4kimised', en: 'Negotiations' },
  'neg.title': { et: 'L\u00e4bir\u00e4\u00e4kimised', en: 'Negotiations' },
  'neg.empty': { et: 'L\u00e4bir\u00e4\u00e4kimisi pole veel alustatud.', en: 'No negotiations started yet.' },
  'neg.start': { et: 'Alusta l\u00e4bir\u00e4\u00e4kimist', en: 'Start Negotiation' },
  'neg.vendor_type': { et: 'Teenusepakkuja t\u00fc\u00fcp', en: 'Vendor Type' },
  'neg.vendor_cloud': { et: 'Pilveteenus', en: 'Cloud Service' },
  'neg.vendor_saas': { et: 'SaaS', en: 'SaaS' },
  'neg.vendor_outsourcing': { et: 'Allhange', en: 'Outsourcing' },
  'neg.vendor_hosting': { et: 'Majutus', en: 'Hosting' },
  'neg.vendor_other': { et: 'Muu', en: 'Other' },
  'neg.strategy': { et: 'Strateegia', en: 'Strategy' },
  'neg.generate_strategy': { et: 'Genereeri AI strateegia', en: 'Generate AI Strategy' },
  'neg.generate_email': { et: 'Genereeri e-kiri', en: 'Generate Email' },
  'neg.generating': { et: 'Genereerimine...', en: 'Generating...' },
  'neg.email_draft': { et: 'E-kirja mustand', en: 'Email Draft' },
  'neg.copy': { et: 'Kopeeri', en: 'Copy' },
  'neg.copied': { et: 'Kopeeritud!', en: 'Copied!' },
  'neg.items': { et: 'L\u00e4bir\u00e4\u00e4kimispunktid', en: 'Negotiation Items' },
  'neg.status_pending': { et: 'Ootel', en: 'Pending' },
  'neg.status_drafted': { et: 'Mustand', en: 'Drafted' },
  'neg.status_sent': { et: 'Saadetud', en: 'Sent' },
  'neg.status_responded': { et: 'Vastatud', en: 'Responded' },
  'neg.status_agreed': { et: 'Kokku lepitud', en: 'Agreed' },
  'neg.status_rejected': { et: 'Tagasi l\u00fckatud', en: 'Rejected' },
  'neg.overall_draft': { et: 'Mustand', en: 'Draft' },
  'neg.overall_in_progress': { et: 'K\u00e4imas', en: 'In Progress' },
  'neg.overall_completed': { et: 'L\u00f5petatud', en: 'Completed' },
  'neg.overall_stalled': { et: 'Peatunud', en: 'Stalled' },
  'neg.progress': { et: 'Edenemine', en: 'Progress' },
  'neg.suggested_clause': { et: 'Pakutav klausel', en: 'Suggested Clause' },
  'neg.legal_basis': { et: '\u00d5iguslik alus', en: 'Legal Basis' },
  'neg.back': { et: 'Tagasi nimekirja', en: 'Back to list' },

  // Guardian
  'nav.guardian': { et: 'Lepinguvalvur', en: 'Contract Guardian' },
  'guardian.title': { et: 'Lepinguvalvur', en: 'Contract Guardian' },
  'guardian.subtitle': { et: 'Pidev lepingute monitooring regulatiivsete muudatuste vastu.', en: 'Continuous contract monitoring against regulatory changes.' },
  'guardian.empty': { et: 'Seiratavaid lepinguid pole. Alustage lepingu anal\u00fc\u00fcsist.', en: 'No monitored contracts. Start with a contract analysis.' },
  'guardian.start_monitoring': { et: 'Alusta seiret', en: 'Start Monitoring' },
  'guardian.monitoring_started': { et: 'Seire alustatud!', en: 'Monitoring started!' },
  'guardian.status_active': { et: 'Aktiivne', en: 'Active' },
  'guardian.status_paused': { et: 'Peatatud', en: 'Paused' },
  'guardian.status_archived': { et: 'Arhiveeritud', en: 'Archived' },
  'guardian.pause': { et: 'Peata', en: 'Pause' },
  'guardian.resume': { et: 'J\u00e4tka', en: 'Resume' },
  'guardian.reanalyze': { et: 'Anal\u00fc\u00fcsi uuesti', en: 'Re-analyze' },
  'guardian.reanalyzing': { et: 'Anal\u00fc\u00fcsimine...', en: 'Analyzing...' },
  'guardian.last_analysis': { et: 'Viimane anal\u00fc\u00fcs', en: 'Last analysis' },
  'guardian.score': { et: 'Skoor', en: 'Score' },
  'guardian.alerts_title': { et: 'Teavitused', en: 'Alerts' },
  'guardian.alerts_empty': { et: 'Teavitusi pole.', en: 'No alerts.' },
  'guardian.mark_read': { et: 'M\u00e4rgi loetuks', en: 'Mark as read' },
  'guardian.unread': { et: 'Lugemata', en: 'Unread' },
  'guardian.all_alerts': { et: 'K\u00f5ik teavitused', en: 'All alerts' },
  'guardian.severity_high': { et: 'K\u00f5rge', en: 'High' },
  'guardian.severity_medium': { et: 'Keskmine', en: 'Medium' },
  'guardian.severity_low': { et: 'Madal', en: 'Low' },
  'guardian.reg_updates': { et: 'Regulatiivsed uuendused', en: 'Regulatory Updates' },
  'guardian.reg_empty': { et: 'Regulatiivseid uuendusi pole.', en: 'No regulatory updates.' },
  'guardian.reg_source': { et: 'Allikas', en: 'Source' },
  'guardian.reg_relevance': { et: 'Olulisus', en: 'Relevance' },
  'guardian.reg_affected': { et: 'M\u00f5jutatud artiklid', en: 'Affected articles' },
  'guardian.view_analysis': { et: 'Vaata anal\u00fc\u00fcsi', en: 'View analysis' },
  'guardian.back': { et: 'Tagasi valvurisse', en: 'Back to Guardian' },

  // Pricing page
  'nav.pricing': { et: 'Hinnad', en: 'Pricing' },
  'pricing.title': { et: 'Valige oma plaan', en: 'Choose your plan' },
  'pricing.subtitle': { et: 'Alustage tasuta ja skaleerige vastavalt vajadusele', en: 'Start free and scale as you need' },
  'pricing.free': { et: 'Tasuta', en: 'Free' },
  'pricing.free_price': { et: '0', en: '0' },
  'pricing.free_desc': { et: 'Proovige toodet ilma kohustuseta', en: 'Try the product with no commitment' },
  'pricing.free_f1': { et: 'Demo lepinguanalüüs', en: 'Demo contract analysis' },
  'pricing.free_f2': { et: 'Enesehindamise küsimustik', en: 'Self-assessment questionnaire' },
  'pricing.free_f3': { et: 'Näidislepingu genereerimine', en: 'Sample contract generation' },
  'pricing.free_f4': { et: '1 lepingu analüüs kuus', en: '1 contract analysis per month' },
  'pricing.free_cta': { et: 'Alusta tasuta', en: 'Start free' },
  'pricing.pro': { et: 'Pro', en: 'Pro' },
  'pricing.pro_price': { et: '149', en: '149' },
  'pricing.pro_period': { et: '/kuu', en: '/month' },
  'pricing.pro_desc': { et: 'Professionaalsetele meeskondadele', en: 'For professional teams' },
  'pricing.pro_f1': { et: 'Piiramatu lepinguanalüüs', en: 'Unlimited contract analysis' },
  'pricing.pro_f2': { et: 'PDF aruannete eksport', en: 'PDF report export' },
  'pricing.pro_f3': { et: 'Hindamiste ajalugu ja trendid', en: 'Assessment history and trends' },
  'pricing.pro_f4': { et: 'Lepinguvalvur (monitoring)', en: 'Contract Guardian (monitoring)' },
  'pricing.pro_f5': { et: 'Intsidendisimulaator', en: 'Incident simulator' },
  'pricing.pro_f6': { et: 'Vastavustunnistus', en: 'Compliance certificate' },
  'pricing.pro_f7': { et: 'E-posti tugi', en: 'Email support' },
  'pricing.pro_cta': { et: 'Alusta Pro plaaniga', en: 'Start Pro plan' },
  'pricing.popular': { et: 'Populaarseim', en: 'Most popular' },
  'pricing.enterprise': { et: 'Enterprise', en: 'Enterprise' },
  'pricing.enterprise_price': { et: 'Kokkuleppel', en: 'Custom' },
  'pricing.enterprise_desc': { et: 'Suurettevõtetele ja kontsernidele', en: 'For large enterprises and groups' },
  'pricing.enterprise_f1': { et: 'Kõik Pro funktsionaalsused', en: 'All Pro features' },
  'pricing.enterprise_f2': { et: 'API ligipääs integratsioonideks', en: 'API access for integrations' },
  'pricing.enterprise_f3': { et: 'Kohandatud vastavusreeglid', en: 'Custom compliance rules' },
  'pricing.enterprise_f4': { et: 'Dedikeeritud projektijuht', en: 'Dedicated project manager' },
  'pricing.enterprise_f5': { et: 'SLA ja prioriteetne tugi', en: 'SLA and priority support' },
  'pricing.enterprise_f6': { et: 'On-premise paigaldus võimalik', en: 'On-premise deployment available' },
  'pricing.enterprise_f7': { et: 'Audit trail ja compliance logging', en: 'Audit trail and compliance logging' },
  'pricing.enterprise_cta': { et: 'Võta ühendust', en: 'Contact us' },
  'pricing.faq_title': { et: 'Korduma kippuvad küsimused', en: 'Frequently asked questions' },
  'pricing.faq1_q': { et: 'Kas ma saan enne ostmist proovida?', en: 'Can I try before buying?' },
  'pricing.faq1_a': { et: 'Jah! Tasuta plaan võimaldab teil analüüsida ühe lepingu kuus ja kasutada enesehindamist piiramatult.', en: 'Yes! The free plan lets you analyze one contract per month and use the self-assessment unlimited.' },
  'pricing.faq2_q': { et: 'Kuidas toimub maksmine?', en: 'How does billing work?' },
  'pricing.faq2_a': { et: 'Pro plaan on igakuise maksega. Saate igal ajal tühistada. Enterprise plaanid on aastase lepinguga.', en: 'Pro plan is billed monthly. You can cancel anytime. Enterprise plans are on annual contracts.' },
  'pricing.faq3_q': { et: 'Kas andmed on turvalised?', en: 'Is my data secure?' },
  'pricing.faq3_a': { et: 'Jah. Kõik andmed töödeldakse EL serverites, lepinguid ei salvestata pärast analüüsi ja me oleme GDPR-konformsed.', en: 'Yes. All data is processed on EU servers, contracts are not stored after analysis, and we are GDPR compliant.' },
  'pricing.faq4_q': { et: 'Kas on API saadaval?', en: 'Is an API available?' },
  'pricing.faq4_a': { et: 'API on saadaval Enterprise plaanis. See võimaldab automatiseerida lepinguanalüüse ja integreerida oma süsteemidega.', en: 'API is available in the Enterprise plan. It allows automating contract analysis and integrating with your systems.' },
  'pricing.guarantee': { et: '30 päeva raha tagasi garantii kõigil tasulistel plaanidel', en: '30-day money-back guarantee on all paid plans' },

  // About page
  'nav.about': { et: 'Meist', en: 'About' },
  'about.title': { et: 'DORA Art. 30 meeskond', en: 'DORA Art. 30 Team' },
  'about.subtitle': { et: 'Ehitame Eesti finantssektorile automatiseeritud vastavuskontrolli', en: 'Building automated compliance checking for the Estonian financial sector' },
  'about.mission_title': { et: 'Meie missioon', en: 'Our mission' },
  'about.mission_desc': { et: 'DORA regulatsioon nõuab kõigilt finantssektori ettevõtetelt, et nende IKT-lepingud vastaksid rangetele nõuetele. Me automatiseerime selle kontrolli, säästes teile aega ja raha.', en: 'DORA regulation requires all financial sector companies to have ICT contracts that meet strict requirements. We automate this check, saving you time and money.' },
  'about.why_title': { et: 'Miks me seda teeme', en: 'Why we do this' },
  'about.why_1': { et: 'DORA kohaldub alates 2025. aastast kõigile EL finantssektori ettevõtetele', en: 'DORA applies from 2025 to all EU financial sector companies' },
  'about.why_2': { et: 'Manuaalne lepingute kontroll on aeglane ja kallis (juristide tunnihind 200-400 EUR)', en: 'Manual contract review is slow and expensive (lawyer hourly rate 200-400 EUR)' },
  'about.why_3': { et: 'Trahvid mittevastavuse eest võivad ulatuda kuni 2% aastasest käibest', en: 'Fines for non-compliance can reach up to 2% of annual turnover' },
  'about.why_4': { et: 'Eestis puudus seni eestikeelne automatiseeritud lahendus', en: 'Estonia lacked an Estonian-language automated solution until now' },
  'about.team_title': { et: 'Meeskond', en: 'Team' },
  'about.team_desc': { et: 'Regulatiivse ekspertiisi ja tehnoloogia kooslus', en: 'A blend of regulatory expertise and technology' },
  'about.role_ceo': { et: 'Asutaja ja tegevjuht', en: 'Founder & CEO' },
  'about.role_cto': { et: 'Tehniline juht', en: 'CTO' },
  'about.role_compliance': { et: 'Vastavusjuht', en: 'Compliance Lead' },
  'about.role_legal': { et: 'Juriidiline nõustaja', en: 'Legal Advisor' },
  'about.bio_ceo': { et: '10+ aastat fintech ja regulatiivses valdkonnas. Endine Finantsinspektsiooni nõunik.', en: '10+ years in fintech and regulatory domain. Former Finantsinspektsioon advisor.' },
  'about.bio_cto': { et: 'Full-stack arendaja, AI/ML ekspert. Ehitanud lahendusi pangandusele ja kindlustusele.', en: 'Full-stack developer, AI/ML expert. Built solutions for banking and insurance.' },
  'about.bio_compliance': { et: 'CISA sertifikaat. 8 aastat kogemust IT-auditeerimises ja vastavuskontrollis.', en: 'CISA certified. 8 years experience in IT auditing and compliance checking.' },
  'about.bio_legal': { et: 'Finants- ja IT-õiguse advokaat. Nõustanud EL regulatsioonide rakendamisel.', en: 'Financial and IT law attorney. Advised on EU regulation implementation.' },
  'about.stats_title': { et: 'Numbrid', en: 'By the numbers' },
  'about.stat_contracts': { et: 'lepingut analüüsitud', en: 'contracts analyzed' },
  'about.stat_orgs': { et: 'organisatsiooni', en: 'organizations' },
  'about.stat_requirements': { et: 'DORA nõuet kontrollitakse', en: 'DORA requirements checked' },
  'about.stat_uptime': { et: 'uptime', en: 'uptime' },
  'about.tech_title': { et: 'Tehnoloogia', en: 'Technology' },
  'about.tech_desc': { et: 'Meie platvorm on ehitatud kaasaegsete tehnoloogiatega ja turvaliselt.', en: 'Our platform is built with modern technologies and securely.' },
  'about.tech_1': { et: 'Andmed ainult EL serverites', en: 'Data only on EU servers' },
  'about.tech_2': { et: 'AES-256 krüpteerimine', en: 'AES-256 encryption' },
  'about.tech_3': { et: 'GDPR-konformne', en: 'GDPR compliant' },
  'about.tech_4': { et: 'Automaatne skaleerumine', en: 'Auto-scaling infrastructure' },
  'about.contact_title': { et: 'Võta ühendust', en: 'Get in touch' },
  'about.contact_desc': { et: 'Küsimused, demo soov või enterprise pakkumine', en: 'Questions, demo request, or enterprise offer' },
  'about.contact_email': { et: 'info@doracheck.eu', en: 'info@doracheck.eu' },

  // Landing - improved testimonials
  'landing.testimonial1_text': { et: 'AI lepinguaudit säästis meile nädalaid konsultandi tasu. Saime kohe teada, millised DORA Art. 30 klauslid puuduvad.', en: 'AI contract audit saved us weeks of consultant fees. We instantly knew which DORA Art. 30 clauses were missing.' },
  'landing.testimonial1_author': { et: 'Mart K.', en: 'Mart K.' },
  'landing.testimonial1_role': { et: 'IT-vastavusjuht, fintech-ettevõte', en: 'IT Compliance Manager, fintech company' },
  'landing.testimonial2_text': { et: 'Radardiagramm annab suurepärase ülevaate. Nüüd teame täpselt, kus peame IKT-lepingutes parandusi tegema.', en: 'Radar chart gives an excellent overview. Now we know exactly where improvements are needed in ICT contracts.' },
  'landing.testimonial2_author': { et: 'Liisa M.', en: 'Liisa M.' },
  'landing.testimonial2_role': { et: 'Riskijuht, kindlustusselts', en: 'Risk Manager, insurance company' },
  'landing.testimonial3_text': { et: 'Kasutame seda regulaarselt kõigi oma IKT-lepingute kontrollimiseks. Professionaalne ja kiire.', en: 'We use it regularly to check all our ICT contracts. Professional and fast.' },
  'landing.testimonial3_author': { et: 'Andres T.', en: 'Andres T.' },
  'landing.testimonial3_role': { et: 'IKT lepingute haldur, pank', en: 'ICT Contract Manager, bank' },
};

@Injectable({ providedIn: 'root' })
export class LangService {
  private langSignal = signal<Lang>((localStorage.getItem('dora_lang') as Lang) || 'et');

  lang = this.langSignal.asReadonly();

  get currentLang(): Lang {
    return this.langSignal();
  }

  toggle() {
    const next: Lang = this.langSignal() === 'et' ? 'en' : 'et';
    this.langSignal.set(next);
    localStorage.setItem('dora_lang', next);
  }

  t(key: string): string {
    const entry = TRANSLATIONS[key];
    if (!entry) return key;
    return entry[this.langSignal()] || entry['et'] || key;
  }
}
